using GAME;
using System;
using System.Collections.Generic;

namespace BattleTriggerClient
{
	public class BattleTriggerEditorInfo
	{
		public static BattleTriggerEditorInfo m_Instance;

		private BattleTriggerParamType[] m_TriggerParam;

		private BattleActionParamType[] m_ActionParam;

		private List<BattleRoomType> m_arRoomType;

		private List<BattleCharATB> m_arCharATB;

		private List<NkBattleTutorialUI> m_arTutorialUI;

		private string[] m_szParamName;

		public static BattleTriggerEditorInfo GetInstance()
		{
			if (BattleTriggerEditorInfo.m_Instance == null)
			{
				BattleTriggerEditorInfo.m_Instance = new BattleTriggerEditorInfo();
				BattleTriggerEditorInfo.m_Instance.SetInfo();
			}
			return BattleTriggerEditorInfo.m_Instance;
		}

		protected void SetInfo()
		{
			this.m_TriggerParam = new BattleTriggerParamType[21];
			this.m_ActionParam = new BattleActionParamType[54];
			this.m_arRoomType = new List<BattleRoomType>();
			this.m_arCharATB = new List<BattleCharATB>();
			this.m_arTutorialUI = new List<NkBattleTutorialUI>();
			this.SetParamName();
			this.SetTriggerInfo("NONE", TRIGGERKIND.TRIGGERKIND_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("STARTWAR", TRIGGERKIND.TRIGGERKIND_STARTWAR, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("MONSTERKILL", TRIGGERKIND.TRIGGERKIND_MONSTERKILL, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_COUNT, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("AREAENTER", TRIGGERKIND.TRIGGERKIND_AREAENTER, PARAMTYPE.PARAMTYPE_AREAINDEX, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("CHECKTURN", TRIGGERKIND.TRIGGERKIND_CHECKTURN, PARAMTYPE.PARAMTYPE_COUNT, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("CHECKQUEST", TRIGGERKIND.TRIGGERKIND_CHECKQUEST, PARAMTYPE.PARAMTYPE_QUESTIDX, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("CHECKDIFFICULTY", TRIGGERKIND.TRIGGERKIND_CHECKDIFFICULTY, PARAMTYPE.PARAMTYPE_DIFFICULT, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("CHECKSTARTDIFFICULTY", TRIGGERKIND.TRIGGERKIND_CHECKSTARTDIFFICULTY, PARAMTYPE.PARAMTYPE_DIFFICULT, PARAMTYPE.PARAMTYPE_QUESTIDX, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("ALLOWCHAR", TRIGGERKIND.TRIGGERKIND_ALLOWCHAR, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_COUNT, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("DENIALCHAR", TRIGGERKIND.TRIGGERKIND_DENIALCHAR, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("CHECKMONSTER", TRIGGERKIND.TRIGGERKIND_CHECKMONSTER, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_COUNT, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("HPCHECK", TRIGGERKIND.TRIGGERKIND_HPCHECK, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("MPCHECK", TRIGGERKIND.TRIGGERKIND_MPCHECK, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("ALLDIED", TRIGGERKIND.TRIGGERKIND_ALLDIED, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("CHARSURVIVED", TRIGGERKIND.TRIGGERKIND_CHARSURVIVED, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_TIME, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_COUNT, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("CHARDIED", TRIGGERKIND.TRIGGERKIND_CHARDIED, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("CHARATTACK", TRIGGERKIND.TRIGGERKIND_CHARATTACK, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("CHARMEET", TRIGGERKIND.TRIGGERKIND_CHARMEET, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("ISCOMPLETEEVENT", TRIGGERKIND.TRIGGERKIND_ISCOMPLETEEVENT, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("CONTINUEBATTLE", TRIGGERKIND.TRIGGERKIND_CONTINUEBATTLE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetTriggerInfo("ALLREADY", TRIGGERKIND.TRIGGERKIND_ALLREADY, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("NONE", ACTIONKIND.ACTIONKIND_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("STOP", ACTIONKIND.ACTIONKIND_STOP, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("START", ACTIONKIND.ACTIONKIND_START, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("VICTORYWAR", ACTIONKIND.ACTIONKIND_VICTORYWAR, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("FAILWAR", ACTIONKIND.ACTIONKIND_FAILWAR, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("LOADEVENT", ACTIONKIND.ACTIONKIND_LOADEVENT, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("TIMEDELAY", ACTIONKIND.ACTIONKIND_TIMEDELAY, PARAMTYPE.PARAMTYPE_TIME, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("MONSTERMAKE", ACTIONKIND.ACTIONKIND_MONSTERMAKE, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_STARTPOS, PARAMTYPE.PARAMTYPE_GRIDID, PARAMTYPE.PARAMTYPE_GRIDPOS, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_COUNT, PARAMTYPE.PARAMTYPE_CHARATB, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("CHARERASE", ACTIONKIND.ACTIONKIND_CHARERASE, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_STARTPOS, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("SHOWTEXT", ACTIONKIND.ACTIONKIND_SHOWTEXT, PARAMTYPE.PARAMTYPE_TEXTINDEX, PARAMTYPE.PARAMTYPE_TIME, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_LEFTRIGHT, PARAMTYPE.PARAMTYPE_ACTIONTIME, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("STARTPOS", ACTIONKIND.ACTIONKIND_STARTPOS, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_STARTPOS, PARAMTYPE.PARAMTYPE_POSX, PARAMTYPE.PARAMTYPE_POSY, PARAMTYPE.PARAMTYPE_POSZ, PARAMTYPE.PARAMTYPE_HORIZON, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("MONBATCH", ACTIONKIND.ACTIONKIND_MONBATCH, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_POSX, PARAMTYPE.PARAMTYPE_POSY, PARAMTYPE.PARAMTYPE_POSZ, PARAMTYPE.PARAMTYPE_HORIZON, PARAMTYPE.PARAMTYPE_CHARATB, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("REWARD", ACTIONKIND.ACTIONKIND_REWARD, PARAMTYPE.PARAMTYPE_DIFFICULT, PARAMTYPE.PARAMTYPE_EXP, PARAMTYPE.PRARMTYPE_MONEY, PARAMTYPE.PARAMTYPE_ITEMUNIQUE, PARAMTYPE.PARAMTYPE_COUNT, PARAMTYPE.PARAMTYPE_ITEMUNIQUE, PARAMTYPE.PARAMTYPE_COUNT, PARAMTYPE.PARAMTYPE_ITEMUNIQUE, PARAMTYPE.PARAMTYPE_COUNT, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("TURNTIME", ACTIONKIND.ACTIONKIND_TURNTIME, PARAMTYPE.PARAMTYPE_TIME, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("MONGROUPPOS", ACTIONKIND.ACTIONKIND_MONGROUPPOS, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_COUNT, PARAMTYPE.PARAMTYPE_POSX, PARAMTYPE.PARAMTYPE_POSY, PARAMTYPE.PARAMTYPE_POSZ, PARAMTYPE.PARAMTYPE_HORIZON, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("CONTINUE_BATTLE_STATE", ACTIONKIND.ACTIONKIND_CONTINUEBATTLESTATE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_PROBABILITY, PARAMTYPE.PARAMTYPE_PROBABILITY, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("ADD_ATTACKSTATE", ACTIONKIND.ACTIONKIND_ADDATTACKSTATE, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_PROBABILITY, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("TUTORIAL", ACTIONKIND.ACTIONKIND_TUTORIAL, PARAMTYPE.PARAMTYPE_UI, PARAMTYPE.PARAMTYPE_TEXTINDEX, PARAMTYPE.PARAMTYPE_TIME, PARAMTYPE.PARAMTYPE_ACTIONTIME, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("MAX_CONTINUEBATTLE_COUNT", ACTIONKIND.ACTIONKIND_MAXCONTINUEBATTLECOUNT, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("DIRECTION", ACTIONKIND.ACTIONKIND_DIRECTION, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("SHOWUI", ACTIONKIND.ACTIONKIND_SHOWUI, PARAMTYPE.PARAMTYPE_UI, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("ANGER_POINT", ACTIONKIND.ACTIONKIND_ANGERPOINT, PARAMTYPE.PARAMTYPE_STARTPOS, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("TUTORIAL_BATCH", ACTIONKIND.ACTIONKIND_TUTORIAL_BATCH, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_GRIDPOS, PARAMTYPE.PARAMTYPE_LEVEL, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("CHANGEHP", ACTIONKIND.ACTIONKIND_CHANGEHP, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("IS MAKE MOKET", ACTIONKIND.ACTIONKIND_ISMAKEMOKET, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("ANIMATION", ACTIONKIND.ACTIONKIND_ANIMATION, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_ANIMATION, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("CUTSCENE_CAMERA", ACTIONKIND.ACTIONKIND_CUTSCENE_CAMERA, PARAMTYPE.PARAMTYPE_DRAMACODE, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_ANIMATION, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("TURNALLY", ACTIONKIND.ACTIONKIND_TURNALLY, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("INPUTCONTROL", ACTIONKIND.ACTIONKIND_INPUTCONTROL, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("CHARWARP", ACTIONKIND.ACTIONKIND_CHARWARP, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_POSX, PARAMTYPE.PARAMTYPE_POSY, PARAMTYPE.PARAMTYPE_POSZ, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("RANDOMCHAT", ACTIONKIND.ACTIONKIND_RANDOMCHAT, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_TIME, PARAMTYPE.PARAMTYPE_PROBABILITY, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("NPCMODE", ACTIONKIND.ACTIONKIND_NPCMODE, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("EFFECT", ACTIONKIND.ACTIONKIND_EFFECT, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_STARTPOS, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_POSX, PARAMTYPE.PARAMTYPE_POSZ, PARAMTYPE.PARAMTYPE_EFFECTCODE, PARAMTYPE.PARAMTYPE_NAME, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("FAILEVENT", ACTIONKIND.ACTIONKIND_FAILEVENT, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("GIVEITEM", ACTIONKIND.ACTIONKIND_GIVEITEM, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_ITEMUNIQUE, PARAMTYPE.PARAMTYPE_COUNT, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("SOUND", ACTIONKIND.ACTIONKIND_SOUND, PARAMTYPE.PARAMTYPE_SOUNDDOMAIN, PARAMTYPE.PARAMTYPE_SOUNDCATEGORY, PARAMTYPE.PARAMTYPE_SOUNDKEY, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("CAMERAMOVETARGET", ACTIONKIND.ACTIONKIND_CAMERAMOVETARGET, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_TIME, PARAMTYPE.PARAMTYPE_ACTIONTIME, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("BGM", ACTIONKIND.ACTIONKIND_BGM, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("CHARATB", ACTIONKIND.ACTIONKIND_CHARATB, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_CHARATB, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("ACTIVE GRID", ACTIONKIND.ACTIONKIND_ACTIVEGRID, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_STARTPOS, PARAMTYPE.PARAMTYPE_GRIDID, PARAMTYPE.PARAMTYPE_GRIDPOS, PARAMTYPE.PARAMTYPE_SIZEX, PARAMTYPE.PARAMTYPE_SIZEY, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("CHANGE CHAR", ACTIONKIND.ACTIONKIND_CHANGECHAR, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_STARTPOS, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("DAMAGE", ACTIONKIND.ACTIONKIND_DAMAGE, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_STARTPOS, PARAMTYPE.PARAMTYPE_GRIDPOS, PARAMTYPE.PARAMTYPE_SIZEX, PARAMTYPE.PARAMTYPE_SIZEY, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("PRELOADINGKIND", ACTIONKIND.ACTIONKIND_PRELOADINGKIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_KIND);
			this.SetActionInfo("RESETEVENT", ACTIONKIND.ACTIONKIND_RESETEVENT, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("FIRSTTURN", ACTIONKIND.ACTIONKIND_FIRSTTURN, PARAMTYPE.PARAMTYPE_ALLY, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("ONEBATTLE", ACTIONKIND.ACTIONKIND_ONEBATTLE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("ALLKILLOFF", ACTIONKIND.ACTIONKIND_ALLKILLOFF, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("CAMERA", ACTIONKIND.ACTIONKIND_CAMERA, PARAMTYPE.PARAMTYPE_TYPE, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_POSX, PARAMTYPE.PARAMTYPE_POSY, PARAMTYPE.PARAMTYPE_POSZ, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("CONTINUE_BOSS", ACTIONKIND.ACTIONKIND_CONTINUEBOSS, PARAMTYPE.PARAMTYPE_PROBABILITY, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE);
			this.SetActionInfo("SKILLONOFF", ACTIONKIND.ACTIONKIND_SKILLONOFF, PARAMTYPE.PARAMTYPE_KIND, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
			this.SetActionInfo("MOVIESTART", ACTIONKIND.ACTIONKIND_MOVIESTART, PARAMTYPE.PARAMTYPE_VALUE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE, PARAMTYPE.PARAMTYPE_NONE);
		}

		protected void SetTriggerInfo(string szName, TRIGGERKIND eKind, PARAMTYPE Param1, PARAMTYPE Param2, PARAMTYPE Param3, PARAMTYPE Param4, PARAMTYPE Param5, PARAMTYPE Param6, PARAMTYPE Param7, PARAMTYPE Param8, PARAMTYPE Param9, PARAMTYPE Param10, PARAMTYPE Param11, PARAMTYPE Param12, PARAMTYPE Param13, PARAMTYPE Param14, PARAMTYPE Param15)
		{
			this.m_TriggerParam[(int)eKind] = new BattleTriggerParamType(szName, eKind, Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, Param9, Param10, Param11, Param12, Param13, Param14, Param15);
		}

		protected void SetActionInfo(string szName, ACTIONKIND eKind, PARAMTYPE Param1, PARAMTYPE Param2, PARAMTYPE Param3, PARAMTYPE Param4, PARAMTYPE Param5, PARAMTYPE Param6, PARAMTYPE Param7, PARAMTYPE Param8, PARAMTYPE Param9, PARAMTYPE Param10, PARAMTYPE Param11, PARAMTYPE Param12, PARAMTYPE Param13, PARAMTYPE Param14, PARAMTYPE Param15)
		{
			this.m_ActionParam[(int)eKind] = new BattleActionParamType(szName, eKind, Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, Param9, Param10, Param11, Param12, Param13, Param14, Param15);
		}

		protected void SetParamName()
		{
			BattleRoomType battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_NONE;
			battleRoomType.m_szRoomTypename = "NONE";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_NORMAL;
			battleRoomType.m_szRoomTypename = "NORMAL";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_SCENARIO;
			battleRoomType.m_szRoomTypename = "SCENARIO";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_PVE;
			battleRoomType.m_szRoomTypename = "PVE";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_PVP;
			battleRoomType.m_szRoomTypename = "PVP";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_PLUNDER;
			battleRoomType.m_szRoomTypename = "PLUNDER";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_COLOSSEUM;
			battleRoomType.m_szRoomTypename = "COLOSSEUM";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_BABELTOWER;
			battleRoomType.m_szRoomTypename = "BABELTOWER";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_MINE;
			battleRoomType.m_szRoomTypename = "MINE";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_GUILD_BOSS;
			battleRoomType.m_szRoomTypename = "GUILD_BOSS";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_DAILYDUNGEON;
			battleRoomType.m_szRoomTypename = "DAILY_DUNGEON";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_INFINITY;
			battleRoomType.m_szRoomTypename = "INFINITY";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_BOUNTYHUNT;
			battleRoomType.m_szRoomTypename = "BOUNTYHUNT";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_EXPEDITION;
			battleRoomType.m_szRoomTypename = "EXPEDITION";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_TUTORIAL;
			battleRoomType.m_szRoomTypename = "TUTORIAL";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_MYTHRAID;
			battleRoomType.m_szRoomTypename = "MYTHRAID";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_PREVIEW;
			battleRoomType.m_szRoomTypename = "PREVIEW";
			this.m_arRoomType.Add(battleRoomType);
			battleRoomType = new BattleRoomType();
			battleRoomType.m_eRoomType = eBATTLE_ROOMTYPE.eBATTLE_ROOMTYPE_NEWEXPLORATION;
			battleRoomType.m_szRoomTypename = "NEWEXPLORATION";
			this.m_arRoomType.Add(battleRoomType);
			BattleCharATB battleCharATB = new BattleCharATB();
			battleCharATB.m_eCharATB = eBATTLE_CHARSTATEATB.BATTLE_CHARSTATEATB_DISABLE_NONE;
			battleCharATB.m_szATBName = "DISABLE_NONE";
			this.m_arCharATB.Add(battleCharATB);
			battleCharATB = new BattleCharATB();
			battleCharATB.m_eCharATB = eBATTLE_CHARSTATEATB.BATTLE_CHARSTATEATB_DISABLE_MOVE;
			battleCharATB.m_szATBName = "DISABLE_MOVE";
			this.m_arCharATB.Add(battleCharATB);
			battleCharATB = new BattleCharATB();
			battleCharATB.m_eCharATB = eBATTLE_CHARSTATEATB.BATTLE_CHARSTATEATB_DISABLE_ATTACK;
			battleCharATB.m_szATBName = "DISABLE_ATTACK";
			this.m_arCharATB.Add(battleCharATB);
			battleCharATB = new BattleCharATB();
			battleCharATB.m_eCharATB = eBATTLE_CHARSTATEATB.BATTLE_CHARSTATEATB_IMMUNE_SKILL;
			battleCharATB.m_szATBName = "IMMUNE";
			this.m_arCharATB.Add(battleCharATB);
			battleCharATB = new BattleCharATB();
			battleCharATB.m_eCharATB = eBATTLE_CHARSTATEATB.BATTLE_CHARSTATEATB_DISABLE_TURN;
			battleCharATB.m_szATBName = "DISABLE_TURN";
			this.m_arCharATB.Add(battleCharATB);
			battleCharATB = new BattleCharATB();
			battleCharATB.m_eCharATB = eBATTLE_CHARSTATEATB.BATTLE_CHARSTATEATB_IMMORTAL;
			battleCharATB.m_szATBName = "IMMORTAL";
			this.m_arCharATB.Add(battleCharATB);
			battleCharATB = new BattleCharATB();
			battleCharATB.m_eCharATB = eBATTLE_CHARSTATEATB.BATTLE_CHARSTATEATB_SILENCE;
			battleCharATB.m_szATBName = "SILENCE";
			this.m_arCharATB.Add(battleCharATB);
			battleCharATB = new BattleCharATB();
			battleCharATB.m_eCharATB = eBATTLE_CHARSTATEATB.BATTLE_CHARSTATEATB_OBJECT;
			battleCharATB.m_szATBName = "OBJECT";
			this.m_arCharATB.Add(battleCharATB);
			battleCharATB = new BattleCharATB();
			battleCharATB.m_eCharATB = eBATTLE_CHARSTATEATB.BATTLE_CHARSTATEATB_MAGIC_RESIST;
			battleCharATB.m_szATBName = "MAGIC_RESIST";
			this.m_arCharATB.Add(battleCharATB);
			battleCharATB = new BattleCharATB();
			battleCharATB.m_eCharATB = eBATTLE_CHARSTATEATB.BATTLE_CHARSTATEATB_PHYSICAL_RESIST;
			battleCharATB.m_szATBName = "PHYSICAL_RESIST";
			this.m_arCharATB.Add(battleCharATB);
			NkBattleTutorialUI nkBattleTutorialUI = new NkBattleTutorialUI();
			nkBattleTutorialUI.m_szUI = G_ID.NONE.ToString();
			nkBattleTutorialUI.m_eUIID = G_ID.NONE;
			this.m_arTutorialUI.Add(nkBattleTutorialUI);
			nkBattleTutorialUI = new NkBattleTutorialUI();
			nkBattleTutorialUI.m_szUI = G_ID.BATTLE_CONTROL_DLG.ToString();
			nkBattleTutorialUI.m_eUIID = G_ID.BATTLE_CONTROL_DLG;
			this.m_arTutorialUI.Add(nkBattleTutorialUI);
			nkBattleTutorialUI = new NkBattleTutorialUI();
			nkBattleTutorialUI.m_szUI = G_ID.BATTLE_BOSSAGGRO_DLG.ToString();
			nkBattleTutorialUI.m_eUIID = G_ID.BATTLE_BOSSAGGRO_DLG;
			this.m_arTutorialUI.Add(nkBattleTutorialUI);
			nkBattleTutorialUI = new NkBattleTutorialUI();
			nkBattleTutorialUI.m_szUI = G_ID.BATTLE_PLUNDER_TURNCOUNT_DLG.ToString();
			nkBattleTutorialUI.m_eUIID = G_ID.BATTLE_PLUNDER_TURNCOUNT_DLG;
			this.m_arTutorialUI.Add(nkBattleTutorialUI);
			nkBattleTutorialUI = new NkBattleTutorialUI();
			nkBattleTutorialUI.m_szUI = G_ID.UIGUIDE_DLG.ToString();
			nkBattleTutorialUI.m_eUIID = G_ID.UIGUIDE_DLG;
			this.m_arTutorialUI.Add(nkBattleTutorialUI);
			this.m_szParamName = new string[40];
			this.m_szParamName[0] = "NONE";
			this.m_szParamName[1] = "VALUE";
			this.m_szParamName[2] = "ALLY";
			this.m_szParamName[3] = "KIND";
			this.m_szParamName[4] = "AREAINDEX";
			this.m_szParamName[5] = "LEVEL";
			this.m_szParamName[6] = "COUNT";
			this.m_szParamName[7] = "TIME";
			this.m_szParamName[8] = "TEXTINDEX";
			this.m_szParamName[9] = "GRIDPOS";
			this.m_szParamName[10] = "ACTIONTIME";
			this.m_szParamName[11] = "HORIZON";
			this.m_szParamName[12] = "VERTICAL";
			this.m_szParamName[13] = "QEUST_IDX";
			this.m_szParamName[14] = "DIFFICULT";
			this.m_szParamName[15] = "EXP";
			this.m_szParamName[16] = "ITEMUNIQUE";
			this.m_szParamName[17] = "TYPE";
			this.m_szParamName[18] = "MOVECELLPOS";
			this.m_szParamName[19] = "MOVETYPE";
			this.m_szParamName[20] = "PROBABILITY";
			this.m_szParamName[21] = "MONEY";
			this.m_szParamName[22] = "DRAMACODE";
			this.m_szParamName[23] = "EFFECTCODE";
			this.m_szParamName[24] = "NAME";
			this.m_szParamName[25] = "LEFTRIGHT";
			this.m_szParamName[26] = "DOMAIN";
			this.m_szParamName[27] = "CATEGORY";
			this.m_szParamName[28] = "AUDIOKEY";
			this.m_szParamName[29] = "EFFECTLAYER";
			this.m_szParamName[30] = "CHARATB";
			this.m_szParamName[31] = "POS X";
			this.m_szParamName[32] = "POS Z";
			this.m_szParamName[33] = "GRID ID";
			this.m_szParamName[34] = "STARTPOS";
			this.m_szParamName[35] = "X SIZE";
			this.m_szParamName[36] = "Y SIZE";
			this.m_szParamName[37] = "POS Y";
			this.m_szParamName[38] = "UI";
			this.m_szParamName[39] = "ANIMATION";
		}

		public string GetParamName(PARAMTYPE eParamType)
		{
			return this.m_szParamName[(int)eParamType];
		}

		public string[] GetTriggerName()
		{
			string[] array = new string[this.m_TriggerParam.Length];
			for (int i = 0; i < this.m_TriggerParam.Length; i++)
			{
				array[i] = this.m_TriggerParam[i].m_szName;
			}
			return array;
		}

		public int[] GetTriggerKindList()
		{
			int[] array = new int[this.m_TriggerParam.Length];
			for (int i = 0; i < this.m_TriggerParam.Length; i++)
			{
				array[i] = (int)this.m_TriggerParam[i].m_eKind;
			}
			return array;
		}

		public string[] GetActionName()
		{
			string[] array = new string[this.m_ActionParam.Length];
			for (int i = 0; i < this.m_ActionParam.Length; i++)
			{
				if (this.m_ActionParam[i] != null)
				{
					array[i] = this.m_ActionParam[i].m_szName;
				}
			}
			return array;
		}

		public int[] GetActionKindList()
		{
			int[] array = new int[this.m_ActionParam.Length];
			for (int i = 0; i < this.m_ActionParam.Length; i++)
			{
				if (this.m_ActionParam[i] != null)
				{
					array[i] = (int)this.m_ActionParam[i].m_eKind;
				}
			}
			return array;
		}

		public string GetTriggerName(TRIGGERKIND eKind)
		{
			for (int i = 0; i < this.m_TriggerParam.Length; i++)
			{
				if (this.m_TriggerParam[i].m_eKind == eKind)
				{
					return this.m_TriggerParam[i].m_szName;
				}
			}
			return null;
		}

		public string GetActionName(ACTIONKIND eKind)
		{
			for (int i = 0; i < this.m_ActionParam.Length; i++)
			{
				if (this.m_ActionParam[i] != null)
				{
					if (this.m_ActionParam[i].m_eKind == eKind)
					{
						return this.m_ActionParam[i].m_szName;
					}
				}
			}
			return null;
		}

		public PARAMTYPE[] GetParam(BATTLETRIGGERTYPE eType, int eKind)
		{
			if (eType <= BATTLETRIGGERTYPE.TYPE_NONE || eType >= BATTLETRIGGERTYPE.TYPE_MAX)
			{
				return null;
			}
			switch (eType)
			{
			case BATTLETRIGGERTYPE.TYPE_NONE:
				return null;
			case BATTLETRIGGERTYPE.TYPE_EVENT:
				return null;
			case BATTLETRIGGERTYPE.TYPE_TRIGGER:
				return this.m_TriggerParam[eKind].m_eParam;
			case BATTLETRIGGERTYPE.TYPE_ACTION:
				return this.m_ActionParam[eKind].m_eParam;
			default:
				return null;
			}
		}

		public string GetCellATBName(CELLATB eATB)
		{
			return null;
		}

		public string GetCellATBName(int index)
		{
			return null;
		}

		public void SetTriggerHelp(TRIGGERKIND eKind, string[] help)
		{
			for (int i = 0; i < this.m_TriggerParam.Length; i++)
			{
				if (this.m_TriggerParam[i].m_eKind == eKind)
				{
					this.m_TriggerParam[i].SetHelp(help);
				}
			}
		}

		public void SetActionHelp(ACTIONKIND eKind, string[] help)
		{
			for (int i = 0; i < this.m_ActionParam.Length; i++)
			{
				if (this.m_ActionParam[i] != null)
				{
					if (this.m_ActionParam[i].m_eKind == eKind)
					{
						this.m_ActionParam[i].SetHelp(help);
					}
				}
			}
		}

		public string[] GetTriggerHelp(TRIGGERKIND eKind)
		{
			for (int i = 0; i < this.m_TriggerParam.Length; i++)
			{
				if (this.m_TriggerParam[i].m_eKind == eKind)
				{
					return this.m_TriggerParam[i].GetHelp();
				}
			}
			return null;
		}

		public string[] GetActionHelp(ACTIONKIND eKind)
		{
			for (int i = 0; i < this.m_ActionParam.Length; i++)
			{
				if (this.m_ActionParam[i] != null)
				{
					if (this.m_ActionParam[i].m_eKind == eKind)
					{
						return this.m_ActionParam[i].GetHelp();
					}
				}
			}
			return null;
		}

		public string[] GetScenarioTypeToString()
		{
			string[] array = new string[this.m_arRoomType.Count];
			for (int i = 0; i < array.Length; i++)
			{
				array[i] = this.m_arRoomType[i].m_szRoomTypename;
			}
			return array;
		}

		public int GetScenarioTypeFromString(string szType)
		{
			for (int i = 0; i < this.m_arRoomType.Count; i++)
			{
				if (szType == this.m_arRoomType[i].m_szRoomTypename)
				{
					return (int)this.m_arRoomType[i].m_eRoomType;
				}
			}
			return 0;
		}

		public string GetScenarioTypeFromIndex(int Index)
		{
			for (int i = 0; i < this.m_arRoomType.Count; i++)
			{
				if (Index == (int)this.m_arRoomType[i].m_eRoomType)
				{
					return this.m_arRoomType[i].m_szRoomTypename;
				}
			}
			return null;
		}

		public string[] GetCharATBToString()
		{
			string[] array = new string[this.m_arCharATB.Count];
			for (int i = 0; i < array.Length; i++)
			{
				array[i] = this.m_arCharATB[i].m_szATBName;
			}
			return array;
		}

		public int GetCharATBFromName(string szType)
		{
			for (int i = 0; i < this.m_arCharATB.Count; i++)
			{
				if (szType == this.m_arCharATB[i].m_szATBName)
				{
					return (int)this.m_arCharATB[i].m_eCharATB;
				}
			}
			return 0;
		}

		public string GetCharATBNameFromATB(int ATB)
		{
			for (int i = 0; i < this.m_arCharATB.Count; i++)
			{
				if (ATB == (int)this.m_arCharATB[i].m_eCharATB)
				{
					return this.m_arCharATB[i].m_szATBName;
				}
			}
			return null;
		}

		public string[] GetTutorialUIName()
		{
			string[] array = new string[this.m_arTutorialUI.Count];
			for (int i = 0; i < this.m_arTutorialUI.Count; i++)
			{
				array[i] = this.m_arTutorialUI[i].m_szUI;
			}
			return array;
		}
	}
}
