using System;

namespace BattleTriggerClient
{
	public enum TRIGGERKIND
	{
		TRIGGERKIND_NONE,
		TRIGGERKIND_STARTWAR,
		TRIGGERKIND_MONSTERKILL,
		TRIGGERKIND_AREAENTER,
		TRIGGERKIND_CHECKTURN,
		TRIGGERKIND_CHECKQUEST,
		TRIGGERKIND_CHECKDIFFICULTY,
		TRIGGERKIND_CHECKSTARTDIFFICULTY,
		TRIGGERKIND_ALLOWCHAR,
		TRIGGERKIND_DENIALCHAR,
		TRIGGERKIND_CHECKMONSTER,
		TRIGGERKIND_HPCHECK,
		TRIGGERKIND_MPCHECK,
		TRIGGERKIND_ALLDIED,
		TRIGGERKIND_CHARSURVIVED,
		TRIGGERKIND_CHARDIED,
		TRIGGERKIND_CHARATTACK,
		TRIGGERKIND_CHARMEET,
		TRIGGERKIND_ISCOMPLETEEVENT,
		TRIGGERKIND_CONTINUEBATTLE,
		TRIGGERKIND_ALLREADY,
		TRIGGERKIND_MAX
	}
}
