using System;

namespace NPatch
{
	public enum ERRORLEVEL
	{
		SUCCESS,
		ALREADYFINALVERSION = 0,
		ERR_INPUTERROR,
		ERR_LOADSYSTEMINFO,
		ERR_CHECKLOCALINFO,
		ERR_LOADPATCHLIST,
		ERR_LOCALFILEMISSING,
		ERR_LOCALFILEINFO,
		ERR_URLFILE,
		ERR_PACKLIST,
		ERR_NEEDRETRY,
		ERR_CHECK_CHECKSUM,
		ERR_FILEBROKEN,
		ERR_IOEXCEPTION,
		ERR_NETWORKEXCEPTION,
		ERR_INSTALLFAILED,
		ERR_FILEVERIFY,
		ERR_TIMEOUT,
		ERR_ETCERROR
	}
}
