using System;

namespace GAME
{
	public enum E_GUILD_MEMBER_UPDATE_KIND
	{
		MEMBER_UPDATE_KIND_CONNECTED,
		MEMBER_UPDATE_KIND_DISCONNECTED,
		MEMBER_UPDATE_KIND_CHANGED_RANK,
		MEMBER_UPDATE_KIND_CHANGED_MAP,
		MEMBER_UPDATE_KIND_JOINED,
		MEMBER_UPDATE_KIND_LEFT,
		MEMBER_UPDATE_KIND_DISCHARED,
		MEMBER_UPDATE_KIND_NEW_REGULAR,
		MEMBER_UPDATE_KIND_NEW_MASTER
	}
}
