using System;

namespace GAME
{
	public enum E_GUILD_UPDATE_KIND
	{
		GUILD_UPDATE_KIND_CREATED,
		GUILD_UPDATE_KIND_DISBANDED,
		GUILD_UPDATE_KIND_FUND,
		GUILD_UPDATE_KIND_LEVEL,
		GUILD_UPDATE_KIND_MESSAGE
	}
}
