using System;

namespace GAME
{
	public enum E_SOLDIER_UPDATE_INFO_TYPE : byte
	{
		E_SOLDIER_UPDATE_INFO_TYPE_LEVEL,
		E_SOLDIER_UPDATE_INFO_TYPE_EXP,
		E_SOLDIER_UPDATE_INFO_TYPE_STATUS,
		E_SOLDIER_UPDATE_INFO_TYPE_GRADE,
		E_SOLDIER_UPDATE_INFO_TYPE_HP,
		E_SOLDIER_UPDATE_INFO_TYPE_MP,
		E_SOLDIER_UPDATE_INFO_TYPE_MAXHP,
		E_SOLDIER_UPDATE_INFO_TYPE_MAXMP
	}
}
