using System;

namespace GAME
{
	public enum E_SUBCHAR_CREATE_TYPE
	{
		E_SUBCHAR_CREATE_TYPE_NORMAL,
		E_SUBCHAR_CREATE_TYPE_BATTLE_DROP,
		E_SUBCHAR_CREATE_TYPE_HUNTCHAR,
		E_SUBCHAR_CREATE_TYPE_GUARDCHAR,
		E_SUBCHAR_CREATE_TYPE_END
	}
}
