using System;

namespace GAME
{
	public enum eACHIVEMENT_GOOGLE
	{
		LEVELUP_10 = 1,
		LEVELUP_30,
		LEVELUP_50,
		SOLCOMPOSE_01,
		SOLCOMPOSE_20,
		SOLCOMPOSE_30,
		SOLEVOLUTION_01,
		SOLEVOLUTION_10,
		SOLEVOLUTION_30,
		ITEM_UPGRADE_LEVEL_20,
		ITEM_REDUCE_10,
		ITEM_SKILL_01,
		ITEM_SKILL_30,
		ITEM_EQUIP_50,
		ITEM_EQUIP_60,
		ITEM_EQUIP_70,
		BABELTOWER_CLEAR_10,
		BABELTOWER_CLEAR_20,
		BABELTOWER_CLEAR_40,
		BABELTOWER_CLEAR_50,
		BABELTOWER_CLEAR_60,
		COLOSSEUM_CLEAR_10,
		COLOSSEUM_CLEAR_50,
		BATTLE_REPLAY_5
	}
}
