using System;

namespace GAME
{
	public enum eAT2CharEquipPart
	{
		CHAREQUIPPART_WEAPON1,
		CHAREQUIPPART_HELMET,
		CHAREQUIPPART_ARMOR,
		CHAREQUIPPART_GLOVE,
		CHAREQUIPPART_BOOTS,
		CHAREQUIPPART_RING,
		MAX_CHAREQUIPPART_NUM
	}
}
