using System;

namespace GAME
{
	public enum eBATTLE_SKILLDETAILATB
	{
		BATTLE_SKILLDETAILATB_NONE,
		BATTLE_SKILLDETAILATB_AFTERUSED,
		BATTLE_SKILLDETAILATB_ABNOMALCONDITION,
		BATTLE_SKILLDETAILATB_BLOOD_SUCKING = 4,
		BATTLE_SKILLDETAILATB_HEAL = 8,
		BATTLE_SKILLDETAILATB_ANGERLYPOINT = 16,
		BATTLE_SKILLDETAILATB_SUMMON = 32,
		BATTLE_SKILLDETAILATB_SPECIAL_SOL = 64,
		BATTLE_SKILLDETAILATB_SPECIAL_ALLY = 128
	}
}
