using System;

namespace GAME
{
	public enum eBattleSkillJopType
	{
		NOMOVENOBULLETPHYSICS = 1,
		NOMOVENOBULLETMAGIC,
		NOMOVEBULLETPHYSICS,
		NOMOVEBULLETMAGIC,
		MOVENOBULLETPHYSICS,
		MOVENOBULLETMAGIC,
		MOVEBULLETPHYSICS,
		MOVEBULLETMAGIC,
		HALFMOVEBULLETPHYSICS,
		HALFMOVEBULLETMAGIC,
		HALFMOVENOBULLETPHYSICS,
		HALFMOVENOBULLETMAGIC
	}
}
