using System;

namespace GAME
{
	public enum eBATTLE_BATTLESKILL_TARGETTYPE
	{
		eBATTLE_BATTLESKILL_SELF = 1,
		eBATTLE_BATTLESKILL_SELF_FRIEND,
		eBATTLE_BATTLESKILL_ENEMY,
		eBATTLE_BATTLESKILL_ALL
	}
}
