using System;

namespace GAME
{
	public enum eBUNNING_EVENT_WEEK
	{
		eBUNNING_EVENT_WEEK_NONE = -2,
		eBUNNING_EVENT_EVERYDAY,
		eBUNNING_EVENT_SUNDAY,
		eBUNNING_EVENT_MONDAY,
		eBUNNING_EVENT_TUESDAY,
		eBUNNING_EVENT_WEDNESDAY,
		eBUNNING_EVENT_THURSDAY,
		eBUNNING_EVENT_FRIDAY,
		eBUNNING_EVENT_SATURDAY,
		eBUNNING_EVENT_WEEK_MAX
	}
}
