using System;

namespace GAME
{
	public enum eBUNNING_EVENT
	{
		eBUNNING_EVENT_NONE,
		eBUNNING_EVENT_BABELPARTY,
		eBUNNING_EVENT_COLOSSEUM,
		eBUNNING_EVENT_BUFFDAMAGE,
		eBUNNING_EVENT_BUFFDAMAGE1,
		eBUNNING_EVENT_BUFFDAMAGE2,
		eBUNNING_EVENT_BUFFDAMAGE3,
		eBUNNING_EVENT_BUFFDAMAGE4,
		eBUNNING_EVENT_BUFFDAMAGE5,
		eBUNNING_EVENT_BUFFDAMAGE6,
		eBUNNING_EVENT_BUFFDAMAGE7,
		eBUNNING_EVENT_BUFFDAMAGE8,
		eBUNNING_EVENT_BUFFDAMAGE9,
		eBUNNING_EVENT_DAILYDUNGEON,
		eBUNNING_EVENT_DAILYQUEST,
		eBUNNING_EVENT_DAILYQUEST1,
		eBUNNING_EVENT_DAILYQUEST2,
		eBUNNING_EVENT_BOUNTYHUNT,
		eBUNNING_EVENT_GMBUFF1,
		eBUNNING_EVENT_GMBUFF2,
		eBUNNING_EVENT_GMBUFF3,
		eBUNNING_EVENT_GMBUFF4,
		eBUNNING_EVENT_GMBUFF5,
		eBUNNING_EVENT_GMBUFF6,
		eBUNNING_EVENT_BUFFDAMAGE10,
		eBUNNING_EVENT_BUFFDAMAGE11,
		eBUNNING_EVENT_BUFFDAMAGE12,
		eBUNNING_EVENT_BUFFDAMAGE13,
		eBUNNING_EVENT_BUFFDAMAGE14,
		eBUNNING_EVENT_BUFFDAMAGE15,
		eBUNNING_EVENT_BUFFDAMAGE16,
		eBUNNING_EVENT_BUFFDAMAGE17,
		eBUNNING_EVENT_BUFFDAMAGE18,
		eBUNNING_EVENT_BUFFDAMAGE19,
		eBUNNING_EVENT_BUFFDAMAGE20,
		eBUNNING_EVENT_MAX
	}
}
