using System;

namespace GAME
{
	public enum eCHAR_DAY_COUNT
	{
		eNONE = -1,
		eCHAR_DAY_COUNT_JOIN_EXIEDITION_COUNT,
		eCHAR_DAY_COUNT_JOIN_COLOSSEUM_COUNT,
		eCHAR_DAY_COUNT_USE_WILL_COUNT,
		eCHAR_DAY_COUNT_REQUEST_FRIENDSOL_COUNT,
		eCHAR_DAY_COUNT_REPLAY_BATTLE_COUNT,
		eCHAR_DAY_COUNT_JOIN_MINE_COUNT,
		eCHAR_DAY_COUNT_JOIN_GUILDBOSS_COUNT,
		eCHAR_DAY_COUNT_INVITE_KAKAO_COUNT,
		eCHAR_DAY_COUNT_WIN_BABELTOWER_COUNT,
		eCHAR_DAY_COUNT_WIN_BABELTOWER3_COUNT,
		eCHAR_DAY_COUNT_WIN_BABELTOWER4_COUNT,
		eCHAR_DAY_COUNT_WIN_BABELTOWER5_COUNT,
		eCHAR_DAY_COUNT_WIN_BABELTOWER6_COUNT,
		eCHAR_DAY_COUNT_CLEAR_DAILYDUNGEON,
		eCHAR_DAY_COUNT_WIN_COLOSSEUM_WITHPLAYER_COUNT,
		eCHAR_DAY_COUNT_WIN_HEROWAR_COUNT,
		eCHAR_DAY_COUNT_ENJOY_INFIBATTLE,
		eCHAR_DAY_COUNT_ENJOY_BOUNT_HUNT,
		eCHAR_DAY_COUNT_ENJOY_BABELTOWER_COUNT,
		eCHAR_DAY_COUNT_ENJOY_MYTHRAID_COUNT,
		eCHAR_DAY_COUNT_TIMESHOP_REFRESH_COUNT,
		eCHAR_DAY_DAILYDUNGEON,
		eCHAR_DAY_NEWEXPLORATION
	}
}
