using System;

namespace GAME
{
	public enum eChallenge_OpenUi
	{
		ePLUNDERMAIN = 1,
		eBOUNTYHUNTING,
		eBABELTOWER_MODESELECT,
		eMYTHRAID_MODESELECT,
		eMINE_SEARCH,
		eCOLOSSEUMMAIN,
		eBABEL_GUILDBOSS_MAIN,
		eREFORGEMAIN,
		eSOLEXTRACT,
		eSOLEXTRACT_DUMMY,
		eSOLTRANSCENDENCE,
		eSOLTRANSCENDENCE_DUMMY,
		eSOLRECRUIT,
		eSOLRECRUIT_DUMMY,
		eSTORYCHAT,
		eBABELTOWERMAIN,
		eREDUCEMAIN,
		eITEMSKILL,
		eSOLDETAIL,
		eITEMMALL,
		eITEMMALL_DUMMY,
		eSOLCOMPOSE_DUMMY,
		eSOLEVOLUTION_DUMMY,
		eDAILYDUNGEON,
		eNEWEXPLORATION,
		eSOLCOMPOSE
	}
}
