using System;

namespace GAME
{
	public enum eCHAR_DETAIL_INFO
	{
		eCHAR_DETAIL_INFO_EVENTTRIGGER = 1,
		eCHAR_DETAIL_INFO_BUY_ITEM,
		eCHAR_DETAIL_INFO_BUY_ITEM_MATERIAL,
		eCHAR_DETAIL_INFO_FRIEND_DEL_COUNT,
		eCHAR_DETAIL_INFO_DAYQUEST_UNIQUE,
		eCHAR_DETAIL_INFO_HEROTICKET_MAX,
		eCHAR_DETAIL_INFO_EQUIPTICKET_MAX,
		eCHAR_DETAIL_INFO_DAY_MINE_JOIN_COUNT,
		eCHAR_DETAIL_INFO_LIMIT_HELPSOL_GIVEITEMCOUNT,
		eCHAR_DETAIL_INFO_DAY_EXPEDITION_JOIN_COUNT,
		eCHAR_DETAIL_INFO_DAY_REWARD = 12,
		eCHAR_DETAIL_INFO_DAY_DAYPLAYTIME,
		eCHAR_DETAIL_INFO_DAY_GMHELP_COUNT,
		eCHAR_DETAIL_INFO_EVENT_LIMIT,
		eCHAR_DETAIL_INFO_LIMIT_COUNT,
		eCHAR_DETAIL_INFO_DAY_LIMIT_COUNT1,
		eCHAR_DETAIL_INFO_DAY_LIMIT_COUNT2,
		eCHAR_DETAIL_INFO_AUCTION_DAILY_SELL_LIMIT,
		eCHAR_DETAIL_INFO_AUCTION_DAILY_BUY_LIMIT,
		eCHAR_DETAIL_INFO_DAY_INFIBATTLE_COUNT,
		eCHAR_DETAIL_INFO_FRIEND_MAIL_SEND_COUNT,
		eCHAR_DETAIL_INFO_DAILY_ATTEND,
		eCHAR_DETAIL_INFO_VIP_FASTBATTLE_ADD_COUNT,
		eCHAR_DETAIL_INFO_DAY_LIMIT_COUNT3,
		eCHAR_DETAIL_INFO_MAX
	}
}
