using System;

namespace GAME
{
	public enum eCharAnimationEventType
	{
		ANIEVENT_ANIMATIONEND,
		ANIEVENT_HIT,
		ANIEVENT_HIT1,
		ANIEVENT_HIT2,
		ANIEVENT_HIT3,
		ANIEVENT_HIT4,
		ANIEVENT_EFFECTSTART,
		ANIEVENT_EFFECTEND,
		ANIEVENT_SLOWSTART,
		ANIEVENT_SLOWEND,
		END_ANIEVENTTYPE
	}
}
