using System;

namespace GAME
{
	public enum eCHAR_LIMIT_COUNT
	{
		eCHAR_LIMIT_COUNT_BABEL_REPEAT,
		eCHAR_LIMIT_COUNT_WILLCHARGE_MONEY,
		eCHAR_LIMIT_COUNT_REPORT_USER,
		eCHAR_LIMIT_COUNT_COLOSSEUM_DAYGIVEITEM
	}
}
