using System;

namespace GAME
{
	public enum eCOLOSSEUM_GRADE
	{
		eCOLOSSEUM_GRADE_BRONZE,
		eCOLOSSEUM_GRADE_SILVER,
		eCOLOSSEUM_GRADE_GOLD,
		eCOLOSSEUM_GRADE_PLATINUM,
		eCOLOSSEUM_GRADE_DIAMOND,
		eCOLOSSEUM_GRADE_ROYAL,
		eCOLOSSEUM_GRADE_MAX
	}
}
