using System;

namespace GAME
{
	public enum eCOLOSSEUM_CONSTANT
	{
		eCOLOSSEUM_CONSTANT_MATCH_RANGE,
		eCOLOSSEUM_CONSTANT_NEXT_MATCH_TIME,
		eCOLOSSEUM_CONSTANT_MATCH_CYCLE,
		eCOLOSSEUM_CONSTANT_DUMMY_MATCH_LOST,
		eCOLOSSEUM_CONSTANT_DUMMY_MATCH_TIME,
		eCOLOSSEUM_CONSTANT_CHECK_LEVEL,
		eCOLOSSEUM_CONSTANT_START_MATCH_TIME,
		eCOLOSSEUM_CONSTANT_BRONZE_UPGRADE_WINCOUNT,
		eCOLOSSEUM_CONSTANT_UPGRADE_RATE,
		eCOLOSSEUM_CONSTANT_DOWNGRADE_RATE,
		eCOLOSSEUM_CONSTANT_ONEDAY_GIVEITEM_LIMITCOUNT,
		eCOLOSSEUM_CONSTANT_LOBBY_TIMELIMIT,
		eCOLOSSEUM_CONSTANT_MAX
	}
}
