using System;

namespace GAME
{
	public enum eCS_USER_BATTLESTATE
	{
		eCS_USER_BATTLESTATE_NONE,
		eCS_USER_BATTLESTATE_BABELTOWER_JOINROOM = 10000,
		eCS_USER_BATTLESTATE_BABELTOWER = 20000,
		eCS_USER_BATTLESTATE_BOUNTYHUNT_JOINROOM = 21000,
		eCS_USER_BATTLESTATE_BOUNTYHUNT = 22000
	}
}
