using System;

namespace GAME
{
	public enum eDAILY_DUNGEON_PARAM
	{
		eDAILY_DUNGEON_PARAM_DIFFICULTY,
		eDAILY_DUNGEON_PARAM_CLEARLEVEL,
		eDAILY_DUNGEON_PARAM_DAY_OF_WEEK,
		eDAILY_DUNGEON_PARAM_DAY
	}
}
