using System;

namespace GAME
{
	public enum eEXPEDITION_CONSTANT
	{
		eEXPEDITION_CONSTANT_ATTACK_TIME = 1,
		eEXPEDITION_CONSTANT_MOVE_TIME,
		eEXPEDITION_CONSTANT_RETURN_TIME,
		eEXPEDITION_CONSTANT_REMAKE_TIME,
		eEXPEDITION_CONSTANT_EXP,
		eEXPEDITION_DAY_COUNT = 7,
		eEXPEDITION_CONSTANT_TUTORIAL_ITEMUNIQUE,
		eEXPEDITION_CONSTANT_TUTORIAL_ITEMNUM,
		eEXPEDITION_CONSTANT_DATA_PROCESSING,
		eEXPEDITION_CONSTANT_SMALL_EXP,
		eEXPEDITION_CONSTANT_MEDIUM_EXP,
		eEXPEDITION_CONSTANT_LARGE_EXP,
		eEXPEDITION_CONSTANT_EXTRALARGE_EXP,
		eEXPEDITION_CONSTANT_MAX
	}
}
