using System;

namespace GAME
{
	public enum eExpeditionSearchDetailInfo_Mode
	{
		eEXPEDITION_DETAILDLG_DEFAULT,
		eEXPEDITION_DETAILDLG_SEARCH,
		eEXPEDITION_DETAILDLG_DEFENCE,
		eEXPEDITION_DETAILDLG_ATTACK,
		eEXPEDITION_DETAILDLG_END
	}
}
