using System;

namespace GAME
{
	public enum eEXPEDITION_STATE
	{
		eEXPEDITION_STATE_NONE,
		eEXPEDITION_STATE_MOVE,
		eEXPEDITION_STATE_BATTLE,
		eEXPEDITION_STATE_OCCBATTLE,
		eEXPEDITION_STATE_BACKMOVE,
		eEXPEDITION_STATE_END
	}
}
