using System;

namespace GAME
{
	public enum eGIVEITEM_TARGET_TYPE
	{
		E_GIVEITEM_TARGET_TYPE_NONE,
		E_GIVEITEM_TARGET_TYPE_USER,
		E_GIVEITEM_TARGET_TYPE_LIVEUSER,
		E_GIVEITEM_TARGET_TYPE_WHOLEUSER
	}
}
