using System;

namespace GAME
{
	public enum eGMHELP_PERSONID
	{
		eGMHELP_PERSONID_1 = 1,
		eGMHELP_PERSONID_2,
		eGMHELP_PERSONID_3,
		eGMHELP_PERSONID_4,
		eGMHELP_PERSONID_5,
		eGMHELP_PERSONID_6,
		eGMHELP_PERSONID_7,
		eGMHELP_PERSONID_8,
		eGMHELP_PERSONID_9,
		eGMHELP_PERSONID_10,
		eGMHELP_PERSONID_MAX
	}
}
