using System;

namespace GAME
{
	public enum eGUILDWAR_TIME_STATE
	{
		eGUILDWAR_TIME_STATE_NONE,
		eGUILDWAR_TIME_STATE_DECLARE,
		eGUILDWAR_TIME_STATE_WARSTART,
		eGUILDWAR_TIME_STATE_WAREND,
		eGUILDWAR_TIME_STATE_RESULT
	}
}
