using System;

namespace GAME
{
	public enum eGUILD_MEMBER_RANK
	{
		GUILD_MEMBER_RANK_NONE,
		GUILD_MEMBER_RANK_INITIATE,
		GUILD_MEMBER_RANK_REGULAR,
		GUILD_MEMBER_RANK_OFFICER,
		GUILD_MEMBER_RANK_SUB_MASTER,
		GUILD_MEMBER_RANK_MASTER,
		GUILD_MEMBER_RANK_MAX
	}
}
