using System;

namespace GAME
{
	public enum eGUILDWAR_MILITARY_STATE
	{
		eGUILDWAR_MILITARY_STATE_NONE,
		eGUILDWAR_MILITARY_STATE_MOVE,
		eGUILDWAR_MILITARY_STATE_MOVECANCEL,
		eGUILDWAR_MILITARY_STATE_WAIT,
		eGUILDWAR_MILITARY_STATE_BATTLE
	}
}
