using System;

namespace GAME
{
	public enum eINVENTORY_TYPE
	{
		eINVENTORY_TYPE_EQUIP_DEFENCE,
		eINVENTORY_TYPE_EQUIP_WEAPON_MELEE,
		eINVENTORY_TYPE_EQUIP_WEAPON_RANGE,
		eINVENTORY_TYPE_EQUIP_WEAPON_MAGIC,
		eINVENTORY_TYPE_SUPPLISE_BOX,
		eINVENTORY_TYPE_MATERIAL_QUEST,
		eINVENTORY_TYPE_TICKET,
		MAX_eINVENTORY_TYPE
	}
}
