using System;

namespace GAME
{
	public enum eITEM_SETTYPE
	{
		eITEM_SETTYPE_INIT = -1,
		eITEM_SETTYPE_DELETE,
		eITEM_SETTYPE_MOVE,
		eITEM_SETTYPE_MAKE,
		eITEM_SETTYPE_BATTLEDROP,
		eITEM_SETTYPE_USE_BOX,
		eITEM_SETTYPE_UPGRADE,
		eITEM_SETTYPE_REPAIR,
		eITEM_SETTYPE_DISASSEMBLE,
		eITEM_SETTYPE_BUYITEM,
		eITEM_SETTYPE_SELITEM,
		eITEM_SETTYPE_MAILBOX,
		eITEM_SETTYPE_COMPOSE,
		eITEM_SETTYPE_QUESTITEM,
		eITEM_SETTYPE_TERRITORYITEM,
		MAX_eITEM_SETTYPE
	}
}
