using System;

namespace GAME
{
	public enum eITEM_OPTION
	{
		ITEMOPTION_DEFAULT,
		ITEMOPTION_DAMAGE,
		ITEMOPTION_DEFENSE,
		ITEMOPTION_CRITICAL,
		ITEMOPTION_HPPLUS,
		ITEMOPTION_MPPLUS,
		ITEMOPTION_HITRATE,
		ITEMOPTION_EVASION,
		MAX_ITEMOPTION_CODE_NUM
	}
}
