using System;

namespace GAME
{
	public enum eITEM_POSTYPE
	{
		INVALID = -1,
		INVEN_ALL,
		INVEN_EQUIP_DEFENCE,
		INVEN_EQUIP_WEAPON_MELEE,
		INVEN_EQUIP_WEAPON_RANGE,
		INVEN_EQUIP_WEAPON_MAGIC,
		INVEN_SUPPLISE_BOX,
		INVEN_MATERIAL_QUEST,
		INVEN_TICKET,
		CHAR_EQUIPPED = 10,
		MAILBOX = 30,
		MAKEITEM = 40,
		MARKET = 100,
		AUCTION = 200,
		MAX_POSTYPE
	}
}
