using System;

namespace GAME
{
	public enum eITEM_OPTION_TYPE
	{
		ITEMOPTION_ABLILITY1,
		ITEMOPTION_ABLILITY2,
		ITEMOPTION_MAKERANK,
		ITEMOPTION_QUALITY,
		ITEMOPTION_BATTLESKILL_UNIQUE,
		ITEMOPTION_BATTLESKILL_LEVEL,
		ITEMOPTION_BATTLESKILL2_UNIQUE,
		ITEMOPTION_ITEMTRADE_COUNT,
		ITEMOPTION_REDUCELEVEL,
		ITEMOPTION_BATTLESKILL2_LEVEL,
		ITEM_OPTION_MAX
	}
}
