using System;

namespace GAME
{
	public enum eITEM_SUPPLY_FUNCTION
	{
		SUPPLY_NORMAL,
		SUPPLY_HPHEAL,
		SUPPLY_MPHEAL,
		SUPPLY_ALLHEAL,
		SUPPLY_EXP,
		SUPPLY_ACTIVEUP,
		SUPPLY_WARP,
		SUPPLY_NEARBYNPC,
		SUPPLY_GETSOLDIER,
		SUPPLY_INJURYCURE,
		SUPPLY_PROTECTTIME,
		SUPPLY_ADDMONEY,
		SUPPLY_BATTLESPEED,
		SUPPLY_QUESTITEM = 100
	}
}
