using System;

namespace GAME
{
	public enum eITEM_TYPE
	{
		ITEMTYPE_NONE,
		ITEMTYPE_SWORD,
		ITEMTYPE_SPEAR,
		ITEMTYPE_AXE,
		ITEMTYPE_BOW,
		ITEMTYPE_GUN,
		ITEMTYPE_CANNON,
		ITEMTYPE_STAFF,
		ITEMTYPE_BIBLE,
		ITEMTYPE_HELMET,
		ITEMTYPE_ARMOR,
		ITEMTYPE_GLOVE,
		ITEMTYPE_BOOTS,
		ITEMTYPE_BOX,
		ITEMTYPE_HEAL,
		ITEMTYPE_QUEST,
		ITEMTYPE_MATERIAL,
		ITEMTYPE_SUPPLY,
		ITEMTYPE_TICKET,
		ITEMTYPE_RING,
		MAX_ITEMTYPE_NUM
	}
}
