using System;

namespace GAME
{
	public enum eLEGION_STATE
	{
		eLEGION_STATE_IDLE,
		eLEGION_STATE_MOVE,
		eLEGION_STATE_BACKMOVE,
		eLEGION_STATE_BATTLE,
		eLEGION_STATE_OCCUPIE_BATTLE_END,
		eLEGION_STATE_OCCUPIE,
		eLEGION_STATE_WAITBATTLE,
		eLEGION_STATE_BACKMOVE_END,
		eLEGION_STATE_END
	}
}
