using System;

namespace GAME
{
	public enum eMINE_MESSAGE
	{
		eMINE_MESSAGE_DEFAULT,
		eMINE_MESSAGE_GO_MILITARY_SUCCESS,
		eMINE_MESSAGE_GO_MILITARY_FAIL01,
		eMINE_MESSAGE_GO_MILITARY_FAIL02,
		eMINE_MESSAGE_GO_MILITARY_FAIL03,
		eMINE_MESSAGE_GO_MILITARY_FAIL04,
		eMINE_MESSAGE_BACKMOVE_MILITARY_SUCCESS,
		eMINE_MESSAGE_BACKMOVE_MILITARY_COMPLETE,
		eMINE_MESSAGE_BACKMOVE_MILITARY_FAIL01
	}
}
