using System;

namespace GAME
{
	public enum eMineSearchDetailInfo_Mode
	{
		eMINE_DETAILDLG_DEFAULT,
		eMINE_DETAILDLG_SEARCH,
		eMINE_DETAILDLG_MYDEFENCE,
		eMINE_DETAILDLG_OTHERDEFENCE,
		eMINE_DETAILDLG_MYATTACK,
		eMINE_DETAILDLG_OTHERATTACK
	}
}
