using System;

namespace GAME
{
	public enum eMINE_CURRENTSTATUS_TYPE
	{
		eMINE_CURRENTSTATUS_OCCUPYGUILD,
		eMINE_CURRENTSTATUS_ATTACKGUILD,
		eMINE_CURRENTSTATUS_MYMILITARY,
		eMINE_CURRENTSTATUS_MAX
	}
}
