using System;

namespace GAME
{
	public enum eNEWGUILD_CONSTANT
	{
		eNEWGUILD_CONSTANT_CREATE_MONEY,
		eNEWGUILD_CONSTANT_LEVEL_FOR_CREATE,
		eNEWGUILD_CONSTANT_MAX_NUM,
		eNEWGUILD_CONSTANT_MAX_MEMBER_NUM,
		eNEWGUILD_CONSTANT_MAX_APPLICANTS_NUM,
		eNEWGUILD_CONSTANT_NEWMASTER_CHECK_DAY,
		eNEWGUILD_CONSTANT_EXP_GET_RATE,
		eNEWGUILD_CONSTANT_NEWBIE_LIMIT_TIME,
		eNEWGUILD_CONSTANT_POST_TEX,
		eNEWGUILD_CONSTANT_ADMIN_NUM,
		eNEWGUILD_CONSTANT_BOSSBATTLECONTRIBUTE,
		eNEWGUILD_CONSTANT_BOSS_CLEARPOINT,
		eNEWGUILD_CONSTANT_BOSSBATTLE_OPENLIMIT_START,
		eNEWGUILD_CONSTANT_BOSSBATTLE_OPENLIMIT_END,
		eNEWGUILD_CONSTANT_BOSSBATTLE_PLAYLIMIT_START,
		eNEWGUILD_CONSTANT_BOSSBATTLE_PLAYLIMIT_END,
		eNEWGUILD_CONSTANT_FUNDGET,
		eNEWGUILD_CONSTANT_GUILDMONEY_EXCHANGE_RATE,
		eNEWGUILD_CONSTANT_GUILDMONEY_DONATE,
		eNEWGUILD_CONSTANT_MERCHANT_HOLDING_TIME,
		eNEWGUILD_CONSTANT_GUILDAGIT_OUTPOS,
		eNEWGUILD_CONSTANT_NPC_HOLDING_TIME,
		eNEWGUILD_CONSTANT_MON_TAMING_TIME,
		eNEWGUILD_CONSTANT_AGIT_MAX_LEVEL,
		eNEWGUILD_CONSTANT_MAX
	}
}
