using System;

namespace GAME
{
	public enum eREINCARNATION_CHARKIND
	{
		eREINCARNATION_CHARKIND_HUMAN_M,
		eREINCARNATION_CHARKIND_HUMAN_F,
		eREINCARNATION_CHARKIND_FURRY_M,
		eREINCARNATION_CHARKIND_FURRY_F,
		eREINCARNATION_CHARKIND_ELF_M,
		eREINCARNATION_CHARKIND_ELF_F,
		eREINCARNATION_CHARKIND_MAX
	}
}
