using System;

namespace GAME
{
	public enum eREMOVE_ITEM_TYPE
	{
		REMOVE_ITEM_GM = 1,
		REMOVE_ITEM_QUEST,
		REMOVE_ITEM_MAKE,
		REMOVE_ITEM_CANCEL_QUEST,
		REMOVE_ITEM_REVIVE_BATTLECHAR,
		REMOVE_ITEM_DEBT,
		REMOVE_ITEM_BABEL_MACRO,
		REMOVE_ITEM_PROTECT1,
		REMOVE_ITEM_PROTECT2
	}
}
