using System;

namespace GAME
{
	public enum eSETITEM_OPTION_TYPE
	{
		eSETITEM_OPTION_TYPE_NONE,
		eSETITEM_OPTION_TYPE_DEF,
		eSETITEM_OPTION_TYPE_MDEF,
		eSETITEM_OPTION_TYPE_ADDHP,
		eSETITEM_OPTION_TYPE_STR,
		eSETITEM_OPTION_TYPE_DEX,
		eSETITEM_OPTION_TYPE_INT,
		eSETITEM_OPTION_TYPE_VIT,
		eSETITEM_OPTION_TYPE_CRIT,
		eSETITEM_OPTION_TYPE_DAMAGE_P,
		eSETITEM_OPTION_TYPE_DAMAGE,
		eSETITEM_OPTION_TYPE_MAX
	}
}
