using System;

namespace GAME
{
	public enum eSKILL_AI_TYPE
	{
		AI_TYPE_AGGROTOP,
		AI_TYPE_HPLOW,
		AI_TYPE_HPTOP,
		AI_TYPE_BUFFTOP,
		AI_TYPE_DEBUFFTOP,
		AI_TYPE_BUFFLOW,
		AI_TYPE_DEBUFFLOW,
		AI_TYPE_BOSSTOP,
		AI_TYPE_NOOVERLAP_AGGROTOP,
		AI_TYPE_NOOVERLAP_HPLOW,
		AI_TYPE_NOOVERLAP_HPTOP,
		AI_TYPE_BUFFTOP_AGGROTOP,
		AI_TYPE_BUFFLOW_AGGROTOP,
		AI_TYPE_BOSSTOP_HPLOW,
		AI_TYPE_NOOVERLAP_TARGETTOP,
		AI_TYPE_HPLOW_NOOVERLAP_CHECK,
		AI_TYPE_HPLOW_DEBUFFTOP_CHECK,
		AI_TYPE_TARGETTOP,
		AI_TYPE_FIND_HEALER_HPLOW_CHECK,
		AI_TYPE_NOOVERLAP
	}
}
