using System;

namespace GAME
{
	public enum eSOL_MILITARY
	{
		SOL_MILITARY_READY,
		SOL_MILITARY_BATTLE,
		SOL_MILITARY_MINE_START,
		SOL_MILITARY_MINE_END = 12,
		SOL_MILITARY_EXPEDITION_START = 50,
		SOL_MILITARY_EXPEDITION_END = 53,
		MAX_SOL_MILITARY_NUM
	}
}
