using System;

namespace GAME
{
	public enum eSOL_SUBDATA
	{
		SOL_SUBDATA_NONE = -1,
		SOL_SUBDATA_STATUSVALUE,
		SOL_SUBDATA_ATTACK_BATTLEPOS,
		SOL_SUBDATA_DEFENCE_BATTLEPOS,
		SOL_SUBDATA_EVOLUTION_EXP,
		SOL_SUBDATA_PVP_BATTLEPOS,
		SOL_SUBDATA_TRADE_COUNT,
		SOL_SUBDATA_FIGHTINGPOWER,
		SOL_SUBDATA_AWAKENING_STRDEX,
		SOL_SUBDATA_MILITARY_LEADER_GROUP,
		SOL_SUBDATA_ATTACK_INFIBATTLE,
		SOL_SUBDATA_DEFENSE_INFIBATTLE,
		SOL_SUBDATA_AWAKENING_INFO,
		SOL_SUBDATA_AWAKENING_VITINT,
		SOL_SUBDATA_COMMONFLAG,
		SOL_SUBDATA_COSTUME,
		SOL_SUBDATA_TRANSCENDENCE_PLUS,
		MAX_SOL_SUBDATA_NUM
	}
}
