using System;

namespace GAME
{
	public enum eSOL_COMBINATION_GRADE
	{
		COMBINATION_GRADE_D,
		COMBINATION_GRADE_C,
		COMBINATION_GRADE_B,
		COMBINATION_GRADE_A,
		COMBINATION_GRADE_S,
		COMBINATION_GRADE_SS,
		COMBINATION_GRADE_EX,
		MAX
	}
}
