using System;

namespace GAME
{
	public enum eSolRecruitType
	{
		SOLRECRUIT_NONE = -1,
		SOLRECRUIT_CASH_ONE,
		SOLRECRUIT_CASH_TEN,
		SOLRECRUIT_TICKET_PLATINUM,
		SOLRECRUIT_TICKET_GOLD,
		SOLRECRUIT_TICKET_SILVER,
		SOLRECRUIT_TICKET_BRONZE,
		SOLRECRUIT_ELEMENT_SOL,
		SOLRECRUIT_TICKET_SELL_INFO,
		SOLRECRUIT_TICKET_RANDOMHEARTSRATE,
		SOLRECRUIT_VOUCHER_FREE_HEARTS_RECRUIT,
		SOLRECRUIT_VOUCHER_CASH1,
		SOLRECRUIT_VOUCHER_CASH11,
		SOLRECRUIT_VOUCHER_FREE_PREMIUM__RECRUIT,
		SOLRECRUIT_ESSENCE_ONE,
		SOLRECRUIT_LEGEND_ELEMENT_SOL,
		SOLRECRUIT_TICKET_FIX_SOL,
		SOLRECRUIT_TICKET_DIAMOND,
		SOLRECRUIT_TICKET_LEGEND,
		SOLRECRUIT_TICKET_PREMIUM,
		SOLRECRUIT_TICKET_MARKET,
		SOLRECRUIT_TICKET_USE11,
		SOLRECRUIT_FREE_PREMIUM_RECRUIT,
		SOLRECRUIT_FREE_HEARTS_RECRUIT,
		MAX_SOLRECRUIT_TICKET_NUM
	}
}
