using System;

namespace GAME
{
	public enum eTIMESHOP_MONEYTYPE
	{
		NONE,
		eTIMESHOP_MONEYTYPE_HEARTS,
		eTIMESHOP_MONEYTYPE_GOLD,
		eTIMESHOP_MONEYTYPE_SOULJAM,
		eTIMESHOP_MONEYTYPE_MYTHELXIR
	}
}
