using System;

namespace GAME
{
	public enum eTRANSCENDENCERANK
	{
		eTRANSCENDENCERANK_RANK_A,
		eTRANSCENDENCERANK_RANK_S,
		eTRANSCENDENCERANK_RANK_SS,
		eTRANSCENDENCERANK_RANK_EX,
		eTRANSCENDENCERANK_RANK_TYPE_MAX
	}
}
