using System;

namespace GAME
{
	public enum eVOUCHER_TYPE
	{
		eVOUCHER_TYPE_NONE,
		eVOUCHER_TYPE_FREE_GIVE_ITEM,
		eVOUCHER_TYPE_FREE_PREMIUM_RECRUIT,
		eVOUCHER_TYPE_RECRUIT_HERO,
		eVOUCHER_TYPE_RECRUIT_HERO_ELEVEN,
		eVOUCHER_TYPE_FREE_HEARTS_RECRUIT,
		eVOUCHER_TYPE_MAX
	}
}
