using System;

namespace GAME
{
	public static class InfiBattleDefine
	{
		public enum eMATCHMODE
		{
			eMATCHMODE_MATCH,
			eMATCHMODE_EXIT
		}

		public enum eINFIBATTLE_STARTRESULT
		{
			eINFIBATTLE_STARTRESULT_WAITTIME = 1,
			eINFIBATTLE_STARTRESULT_NOTPLAYERINFO,
			eINFIBATTLE_STARTRESULT_NOTLEADER,
			eINFIBATTLE_STARTRESULT_DISCONNECT_CS,
			eINFIBATTLE_STARTRESULT_BATTLEMAKE_FAIL,
			eINFIBATTLE_STARTRESULT_RANKSET,
			eINFIBATTLE_STARTRESULT_BATTLE_START
		}

		public enum eINFIBATTLE_RANKMODE
		{
			eINFIBATTLE_RANKMODE_LASTWEEK,
			eINFIBATTLE_RANKMODE_TOTAL,
			eINFIBATTLE_RANKMODE_COMMUNITY,
			eINFIBATTLE_RANKMODE_MAX
		}

		public const int MAX_INFIBATTLE_SOLNUM = 15;

		public const int MAX_INFIBATTLE_STARTPOS_INDEX = 3;

		public const int DEFAULT_RANK_COUNT = 1;

		public const int MAX_RANK_COUNT = 10;
	}
}
