using System;

namespace SERVICE
{
	public enum eAuthPlatformType
	{
		AUTH_PLATFORMTYPE_NONE,
		AUTH_PLATFORMTYPE_NDOORS,
		AUTH_PLATFORMTYPE_FACEBOOK,
		AUTH_PLATFORMTYPE_NEXONPLAY,
		AUTH_PLATFORMTYPE_BAND,
		AUTH_PLATFORMTYPE_KAKAO,
		AUTH_PLATFORMTYPE_GOOGLEPLAY,
		AUTH_PLATFORMTYPE_CHUKONG,
		AUTH_PLATFORMTYPE_LINE,
		AUTH_PLATFORMTYPE_MAX
	}
}
