using System;

namespace SERVICE
{
	public enum eOTPRequestType
	{
		OTPREQ_USERAUTH,
		OTPREQ_CHARPORTRAIT,
		OTPREQ_GUILDMARK,
		OTPREQ_EMAIL,
		OTPREQ_HP_AUTH,
		OTPREQ_GUESTID,
		OTPREQ_HELPQUESTION,
		OTPREQ_UNREGISTER,
		MAX_OTPREQ_TYPE_NUM
	}
}
