using System;

namespace SERVICE
{
	public enum ePlayerPlatformType
	{
		PLAYER_PLATFORMTYPE_NONE,
		PLAYER_PLATFORMTYPE_WEBPLAYER,
		PLAYER_PLATFORMTYPE_AND,
		PLAYER_PLATFORMTYPE_IOS,
		PLAYER_PLATFORMTYPE_MAX
	}
}
