using System;

namespace SERVICE
{
	public enum eStoreType
	{
		STORE_TYPE_NONE,
		STORE_TYPE_WEBPAGE = 0,
		STORE_TYPE_GOOGLEPLAY,
		STORE_TYPE_TSTORE,
		STORE_TYPE_NAVER,
		STORE_TYPE_APPLESTORE,
		STORE_TYPE_CN_COCO = 10,
		STORE_TYPE_MAX
	}
}
