using System;

namespace PROTOCOL.LOGIN.ID
{
	internal enum eLOGIN_PACKET_ID
	{
		PACKET_BEGIN = 2097152,
		LS_ENCRYPTKEY_NFY,
		LS_LOGIN_USER_REQ,
		LS_LOGIN_USER_ACK,
		LS_LOGOUT_USER_REQ,
		LS_LOGOUT_USER_ACK,
		LS_CHANNEL_LIST_REQ,
		LS_CHANNEL_LIST_ACK,
		LS_CHANNEL_INFO_REQ,
		LS_CHANNEL_INFO_ACK,
		LS_PLATFORM_LOGIN_REQ,
		LS_PLATFORM_LOGIN_ACK,
		LS_CHINA_LOGIN_REQ,
		LS_JAPAN_LOGIN_REQ,
		PACKET_END
	}
}
