using System;

namespace IndunTriggerClient
{
	public enum INDUN_ACTIONKIND
	{
		INDUN_ACTIONKIND_NONE,
		INDUN_ACTIONKIND_CHARMAKE,
		INDUN_ACTIONKIND_BATTLEMATCH,
		INDUN_ACTIONKIND_LOADEVENT,
		INDUN_ACTIONKIND_FAILEVENT,
		INDUN_ACTIONKIND_TIMEDELAY,
		INDUN_ACTIONKIND_RESETEVENT,
		INDUN_ACTIONKIND_CHARERASE,
		INDUN_ACTIONKIND_EFFECT,
		INDUN_ACTIONKIND_SHOWTEXT,
		INDUN_ACTIONKIND_VICTORYWAR,
		INDUN_ACTIONKIND_FAILWAR,
		INDUN_ACTIONKIND_ANICONTROL,
		INDUN_ACTIONKIND_INPUTCONTROL,
		INDUN_ACTIONKIND_BLOCKAREA,
		INDUN_ACTIONKIND_INDUNATB,
		INDUN_ACTIONKIND_DRAMA,
		INDUN_ACTIONKIND_CAMERA,
		INDUN_ACTIONKIND_MAX
	}
}
