using System;

namespace IndunTriggerClient
{
	public enum INDUNTRIGGERTYPE
	{
		INDUNTRIGGERTYPE_NONE,
		INDUNTRIGGERTYPE_EVENT,
		INDUNTRIGGERTYPE_TRIGGER,
		INDUNTRIGGERTYPE_ACTION,
		INDUNTRIGGERTYPE_AREA,
		INDUNTRIGGERTYPE_MAX
	}
}
