using System;

namespace IndunTriggerClient
{
	public enum INDUN_TRIGGERKIND
	{
		INDUN_TRIGGERKIND_NONE,
		INDUN_TRIGGERKIND_START,
		INDUN_TRIGGERKIND_AREAENTER,
		INDUN_TRIGGERKIND_ISCOMPLETEEVENT,
		INDUN_TRIGGERKIND_CHECKTIME,
		INDUN_TRIGGERKIND_CHECKCHAR,
		INDUN_TRIGGERKIND_CHECKQUEST,
		INDUN_TRIGGERKIND_MAX
	}
}
