using System;

namespace NXBand
{
	public enum RequestCode
	{
		REQUEST_INIT = 100,
		REQUEST_LOGIN,
		REQUEST_LOGOUT,
		REQUEST_DISCONNECT,
		REQUEST_PROFILE,
		REQUEST_MY_PROFILE,
		REQUEST_USER_KEY,
		REQUEST_LIST_MEMBER,
		REQUEST_LIST_BAND_MEMBER,
		REQUEST_SEND_INVITATION,
		REQUEST_SEND_MESSAGE,
		REQUEST_LIST_BAND,
		REQUEST_WRITE_POST,
		REQUEST_ACCESS_TOKEN,
		REQUEST_QUOTA,
		REQUEST_INVITER,
		REQUEST_CACHE_INFO
	}
}
