using GAME;
using System;
using TsLibs;

public class COMMON_CONSTANT_Manager : NrTableBase
{
	private int[] m_CommonConstant = new int[164];

	private static COMMON_CONSTANT_Manager Instance;

	private NkValueParse<eCOMMON_CONSTANT> m_kConstantCode;

	private COMMON_CONSTANT_Manager(string strFilePath) : base(strFilePath)
	{
		this.m_kConstantCode = new NkValueParse<eCOMMON_CONSTANT>();
		this.SetConstantCode();
	}

	public static COMMON_CONSTANT_Manager GetInstance()
	{
		if (COMMON_CONSTANT_Manager.Instance == null)
		{
			COMMON_CONSTANT_Manager.Instance = new COMMON_CONSTANT_Manager(CDefinePath.COMMON_CONSTANT_URL);
		}
		return COMMON_CONSTANT_Manager.Instance;
	}

	public void SetConstantCode()
	{
		this.m_kConstantCode.InsertCodeValue("LEVEL_FORSOLINDEX1", eCOMMON_CONSTANT.eCOMMON_CONSTANT_LEVEL_FORSOLINDEX1);
		this.m_kConstantCode.InsertCodeValue("LEVEL_FORSOLINDEX2", eCOMMON_CONSTANT.eCOMMON_CONSTANT_LEVEL_FORSOLINDEX2);
		this.m_kConstantCode.InsertCodeValue("LEVEL_FORSOLINDEX3", eCOMMON_CONSTANT.eCOMMON_CONSTANT_LEVEL_FORSOLINDEX3);
		this.m_kConstantCode.InsertCodeValue("LEVEL_FORSOLINDEX4", eCOMMON_CONSTANT.eCOMMON_CONSTANT_LEVEL_FORSOLINDEX4);
		this.m_kConstantCode.InsertCodeValue("LEVEL_FORSOLINDEX5", eCOMMON_CONSTANT.eCOMMON_CONSTANT_LEVEL_FORSOLINDEX5);
		this.m_kConstantCode.InsertCodeValue("SOLCOMPOSE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SOLCOMPOSE);
		this.m_kConstantCode.InsertCodeValue("BASE_ACTIVITY", eCOMMON_CONSTANT.eCOMMON_CONSTANT_BASE_ACTIVITY);
		this.m_kConstantCode.InsertCodeValue("LEVEL_ACTIVITY", eCOMMON_CONSTANT.eCOMMON_CONSTANT_LEVEL_ACTIVITY);
		this.m_kConstantCode.InsertCodeValue("USE_BATTLE_ACTIVITY", eCOMMON_CONSTANT.eCOMMON_CONSTANT_USE_BATTLE_ACTIVITY);
		this.m_kConstantCode.InsertCodeValue("USE_MILITARY_ACTIVITY", eCOMMON_CONSTANT.eCOMMON_CONSTANT_USE_MILITARY_ACTIVITY);
		this.m_kConstantCode.InsertCodeValue("UPDATE_ACTIVITY_MINUTE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_UPDATE_ACTIVITY_MINUTE);
		this.m_kConstantCode.InsertCodeValue("CASH_ITEMUNIQUE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_CASH_ITEMUNIQUE);
		this.m_kConstantCode.InsertCodeValue("CASHCOUNT_FORONE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_CASHCOUNT_FORONE);
		this.m_kConstantCode.InsertCodeValue("CASHCOUNT_FORTEN", eCOMMON_CONSTANT.eCOMMON_CONSTANT_CASHCOUNT_FORTEN);
		this.m_kConstantCode.InsertCodeValue("SOLCOUNT_FORTEN", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SOLCOUNT_FORTEN);
		this.m_kConstantCode.InsertCodeValue("HEARTPOINT_MAX", eCOMMON_CONSTANT.eCOMMON_CONSTANT_HEARTPOINT_MAX);
		this.m_kConstantCode.InsertCodeValue("HEARTPOINT_UPDATETIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_HEARTPOINT_UPDATETIME);
		this.m_kConstantCode.InsertCodeValue("ONEDAY_DELFRIENDCOUNT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_ONEDAY_DELFRIENDCOUNT);
		this.m_kConstantCode.InsertCodeValue("SOL_INJURYRATE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SOL_INJURYRATE);
		this.m_kConstantCode.InsertCodeValue("SOL_INJURYBASETIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SOL_INJURYBASETIME);
		this.m_kConstantCode.InsertCodeValue("SOL_INJURYLEVELTIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SOL_INJURYLEVELTIME);
		this.m_kConstantCode.InsertCodeValue("SOL_INJURYGOLD", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SOL_INJURYGOLD);
		this.m_kConstantCode.InsertCodeValue("SOL_INJURYLEVEL", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SOL_INJURYLEVEL);
		this.m_kConstantCode.InsertCodeValue("SOLTRADE1", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SOL_TRADE1);
		this.m_kConstantCode.InsertCodeValue("SOLTRADE2", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SOL_TRADE2);
		this.m_kConstantCode.InsertCodeValue("SELLPLUNDER", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_SELLMONEYRATE);
		this.m_kConstantCode.InsertCodeValue("OURPLUNDER", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_OURMONEYRATE);
		this.m_kConstantCode.InsertCodeValue("PROTECTTIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_PROTECTTIME);
		this.m_kConstantCode.InsertCodeValue("PLUNDERGOLD", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_MATCHGOLD);
		this.m_kConstantCode.InsertCodeValue("PLUNDERGOLD2", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_MATCHGOLD2);
		this.m_kConstantCode.InsertCodeValue("MATCHGOLD", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_REMATCHGOLD);
		this.m_kConstantCode.InsertCodeValue("SUPPORTPLUNDER", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_SUPPORTPLUNDER);
		this.m_kConstantCode.InsertCodeValue("SUPPORTTIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_SUPPORTTIME);
		this.m_kConstantCode.InsertCodeValue("PLUNDERDELAYTIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_DELAYTIME);
		this.m_kConstantCode.InsertCodeValue("WILL_CHARGE_MONEY1", eCOMMON_CONSTANT.eCOMMON_CONSTANT_WILL_CHARGE_MONEY1);
		this.m_kConstantCode.InsertCodeValue("WILL_CHARGE_MONEY2", eCOMMON_CONSTANT.eCOMMON_CONSTANT_WILL_CHARGE_MONEY2);
		this.m_kConstantCode.InsertCodeValue("PLUNDER_AGREE_ITEM_UNIQUE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_AGREE_ITEM_UNIQUE);
		this.m_kConstantCode.InsertCodeValue("PLUNDER_AGREE_ITEM_NUM", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_AGREE_ITEM_NUM);
		this.m_kConstantCode.InsertCodeValue("PLUNDER_AGREE_GOLD", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_AGREE_GOLD);
		this.m_kConstantCode.InsertCodeValue("AUTO_BATTLE_LV", eCOMMON_CONSTANT.eCOMMON_CONSTANT_AUTO_BATTLE_LV);
		this.m_kConstantCode.InsertCodeValue("KEEP_SKILL_LV_RATE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_KEEP_SKILL_LV_RATE);
		this.m_kConstantCode.InsertCodeValue("BABELTOWER_LV", eCOMMON_CONSTANT.eCOMMON_CONSTANT_BABELTOWER_LIMITLEVEL);
		this.m_kConstantCode.InsertCodeValue("BABEL_EXP", eCOMMON_CONSTANT.eCOMMON_CONSTANT_BABELTOWER_ADDEXPRATE);
		this.m_kConstantCode.InsertCodeValue("BABEL_EXPLIMIT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_BABELTOWER_EXPLIMIT);
		this.m_kConstantCode.InsertCodeValue("EVOLUTION_EXP_RATE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_EVOLUTION_EXP_RATE);
		this.m_kConstantCode.InsertCodeValue("EXPLORATION_LV", eCOMMON_CONSTANT.eCOMMON_CONSTANT_EXPLORATION_LV);
		this.m_kConstantCode.InsertCodeValue("EXPLORATION_EXP", eCOMMON_CONSTANT.eCOMMON_CONSTANT_EXPLORATION_EXP);
		this.m_kConstantCode.InsertCodeValue("RECOMMEND_MAX", eCOMMON_CONSTANT.eCOMMON_CONSTANT_RECOMMEND_MAX);
		this.m_kConstantCode.InsertCodeValue("RECOMMEND_MAX_ACCEPT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_RECOMMEND_MAX_ACCEPT);
		this.m_kConstantCode.InsertCodeValue("ITEMREDUCE_MAX", eCOMMON_CONSTANT.eCOMMON_CONSTANT_ITEMREDUCE_MAX);
		this.m_kConstantCode.InsertCodeValue("EXP_BOOSTER1", eCOMMON_CONSTANT.eCOMMON_CONSTANT_EXP_BOOSTER1);
		this.m_kConstantCode.InsertCodeValue("SOL_TRADE_GRADE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SOL_TRADE_GRADE);
		this.m_kConstantCode.InsertCodeValue("PLUNDER_SHIELD_TIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PLUNDER_SHIELD_TIME);
		this.m_kConstantCode.InsertCodeValue("NPCHELP_LEVEL_MAX", eCOMMON_CONSTANT.eCOMMON_CONSTANT_GMHELP_SOLLEVELMAX);
		this.m_kConstantCode.InsertCodeValue("NPCHELP_LEVEL_MIN", eCOMMON_CONSTANT.eCOMMON_CONSTANT_GMHELP_SOLLEVELMIN);
		this.m_kConstantCode.InsertCodeValue("NPCHELP_NUM", eCOMMON_CONSTANT.eCOMMON_CONSTANT_GMHELP_SOL_MAX_NUM);
		this.m_kConstantCode.InsertCodeValue("MAX_HERO_WAREHOUSE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SOL_WAREHOUSE_MAX);
		this.m_kConstantCode.InsertCodeValue("FREE_HERO_WAREHOUSE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_FREE_HERO_WAREHOUSE);
		this.m_kConstantCode.InsertCodeValue("JOIN_COUNT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_JOIN_COUNT);
		this.m_kConstantCode.InsertCodeValue("SEASON_EVOLUTION_EXP_PENALTY", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SEASON_EVOLUTION_EXP_PENALTY);
		this.m_kConstantCode.InsertCodeValue("RECOMMEND_LV", eCOMMON_CONSTANT.eCOMMON_CONSTANT_RECOMMEND_LEVEL);
		this.m_kConstantCode.InsertCodeValue("RECOMMEND_LV_ACCEPT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_RECOMMEND_LEVEL_ACCEPT);
		this.m_kConstantCode.InsertCodeValue("ITEM_TRADE_LIMIT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_ITEM_TRADE_LIMIT);
		this.m_kConstantCode.InsertCodeValue("SUPPORT_MAX", eCOMMON_CONSTANT.eCOMMON_CONSTANT_SUPPORT_MAX);
		this.m_kConstantCode.InsertCodeValue("FRIENDHELP_LIMIT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_FRIENDHELP_LIMIT);
		this.m_kConstantCode.InsertCodeValue("REPLAY_MINE_AP", eCOMMON_CONSTANT.eCOMMON_CONSTANT_REPLAY_MINE_AP);
		this.m_kConstantCode.InsertCodeValue("REPLAY_PLUNDER_AP", eCOMMON_CONSTANT.eCOMMON_CONSTANT_REPLAY_PLUNDER_AP);
		this.m_kConstantCode.InsertCodeValue("FRIEND_SUPPORT_ITEM_1", eCOMMON_CONSTANT.eCOMMON_CONSTANT_HELPSOLREWARD_ITEMUNIQUE_1);
		this.m_kConstantCode.InsertCodeValue("FRIEND_SUPPORT_ITEM_2", eCOMMON_CONSTANT.eCOMMON_CONSTANT_HELPSOLREWARD_ITEMUNIQUE_2);
		this.m_kConstantCode.InsertCodeValue("BATTLE_REPEAT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_BATTLE_REPEAT);
		this.m_kConstantCode.InsertCodeValue("BATTLE_REPEAT_LIMIT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_BATTLE_REPEAT_LIMIT);
		this.m_kConstantCode.InsertCodeValue("TRADECOUNT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_TRADECOUNT_USE);
		this.m_kConstantCode.InsertCodeValue("WILL_CHARGE_LIMIT1", eCOMMON_CONSTANT.eCOMMON_CONSTANT_WILL_CHARGE_LIMIT1);
		this.m_kConstantCode.InsertCodeValue("WILL_CHARGE_LIMIT2", eCOMMON_CONSTANT.eCOMMON_CONSTANT_WILL_CHARGE_LIMIT2);
		this.m_kConstantCode.InsertCodeValue("WILL_CHARGE_LIMIT3", eCOMMON_CONSTANT.eCOMMON_CONSTANT_WILL_CHARGE_LIMIT3);
		this.m_kConstantCode.InsertCodeValue("WILL_CHARGE_LIMIT4", eCOMMON_CONSTANT.eCOMMON_CONSTANT_WILL_CHARGE_LIMIT4);
		this.m_kConstantCode.InsertCodeValue("WILL_CHARGE_LIMIT5", eCOMMON_CONSTANT.eCOMMON_CONSTANT_WILL_CHARGE_LIMIT5);
		this.m_kConstantCode.InsertCodeValue("WILL_CHARGE_LIMIT6", eCOMMON_CONSTANT.eCOMMON_CONSTANT_WILL_CHARGE_LIMIT6);
		this.m_kConstantCode.InsertCodeValue("INFIBATTLE_RANKLIMIT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_INFIBATTLE_RANKLIMIT);
		this.m_kConstantCode.InsertCodeValue("INFIBATTLE_DAILYLIMIT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_INFIBATTLE_DAILYLIMIT);
		this.m_kConstantCode.InsertCodeValue("INFIBATTLE_DELAYTIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_INFIBATTLE_DELAYTIME);
		this.m_kConstantCode.InsertCodeValue("PROTECT_TIME_BUY1", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PROTECT_TIME_BUY1);
		this.m_kConstantCode.InsertCodeValue("PROTECT_TIME_BUY2", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PROTECT_TIME_BUY2);
		this.m_kConstantCode.InsertCodeValue("PROTECT_TIME_PRICE1", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PROTECT_TIME_PRICE1);
		this.m_kConstantCode.InsertCodeValue("PROTECT_TIME_PRICE2", eCOMMON_CONSTANT.eCOMMON_CONSTANT_PROTECT_TIME_PRICE2);
		this.m_kConstantCode.InsertCodeValue("INFIBATTLE_LEVEL", eCOMMON_CONSTANT.eCOMMON_CONSTANT_INFIBATTLE_LEVEL);
		this.m_kConstantCode.InsertCodeValue("POINT_EXCHANGE_LIMIT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_POINT_EXCHANGE_LIMIT);
		this.m_kConstantCode.InsertCodeValue("GET_ITEMPOINT_VALUE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_GET_ITEMPOINT_VALUE);
		this.m_kConstantCode.InsertCodeValue("WINNING_STREAK1", eCOMMON_CONSTANT.eCOMMON_CONSTANT_WINNING_STREAK1);
		this.m_kConstantCode.InsertCodeValue("WINNING_STREAK2", eCOMMON_CONSTANT.eCOMMON_CONSTANT_WINNING_STREAK2);
		this.m_kConstantCode.InsertCodeValue("WILL_CHARGE_LIMIT_COUNT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_WILL_CHARGE_LIMIT_COUNT);
		this.m_kConstantCode.InsertCodeValue("AWAKENING_ITEM_UNIQUE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_AWAKENING_ITEM_UNIQUE);
		this.m_kConstantCode.InsertCodeValue("BOUNTY_REQUIRE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_BOUNTY_REQUIRE);
		this.m_kConstantCode.InsertCodeValue("BOUNTY_REQUIRE_RANK", eCOMMON_CONSTANT.eCOMMON_CONSTANT_BOUNTY_REQUIRE_RANK);
		this.m_kConstantCode.InsertCodeValue("AWAKENING_LIMIT_LEVEL", eCOMMON_CONSTANT.eCOMMON_CONSTANT_AWAKENING_LIMIT_LEVEL);
		this.m_kConstantCode.InsertCodeValue("CHATLIMIT_WARNNING", eCOMMON_CONSTANT.eCOMMON_CONSTANT_CHATLIMIT_WARNNING);
		this.m_kConstantCode.InsertCodeValue("CHATLIMIT_REACH", eCOMMON_CONSTANT.eCOMMON_CONSTANT_CHATLIMIT_REACH);
		this.m_kConstantCode.InsertCodeValue("CHATLIMIT_LEVEL", eCOMMON_CONSTANT.eCOMMON_CONSTANT_CHATLIMIT_LEVEL);
		this.m_kConstantCode.InsertCodeValue("CHATLIMIT_NUM", eCOMMON_CONSTANT.eCOMMON_CONSTANT_CHATLIMIT_MAXNUM);
		this.m_kConstantCode.InsertCodeValue("CHATLIMIT_TIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_CHATLIMIT_TIME);
		this.m_kConstantCode.InsertCodeValue("BOUNTY_INVITE_LEVEL", eCOMMON_CONSTANT.eCOMMON_CONSTANT_BOUNTY_INVITE_LEVEL);
		this.m_kConstantCode.InsertCodeValue("COLOSSEUM_ENTRY", eCOMMON_CONSTANT.eCOMMON_CONSTANT_TOURNAMENT_JOIN);
		this.m_kConstantCode.InsertCodeValue("VOUCHER_REFILL_TIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_VOUCHER_REFILL_TIME);
		this.m_kConstantCode.InsertCodeValue("FRIEND_MAIL_LIMIT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_FRIEND_MAIL_LIMIT);
		this.m_kConstantCode.InsertCodeValue("DAILYGIFT_GROUPUNIQUE_WEEK", eCOMMON_CONSTANT.eCOMMON_CONSTANT_DAILYGIFT_GROUPUNIQUE_WEEK);
		this.m_kConstantCode.InsertCodeValue("DAILYGIFT_GROUPUNIQUE_HOUR", eCOMMON_CONSTANT.eCOMMON_CONSTANT_DAILYGIFT_GROUPUNIQUE_HOUR);
		this.m_kConstantCode.InsertCodeValue("VIP_EXP", eCOMMON_CONSTANT.eCOMMON_CONSTANT_VIP_EXP);
		this.m_kConstantCode.InsertCodeValue("BABEL_HARD_LEVEL", eCOMMON_CONSTANT.eCOMMON_CONSTANT_BABEL_HARD_LEVEL);
		this.m_kConstantCode.InsertCodeValue("CHARGE_ACTIVITY_MAX", eCOMMON_CONSTANT.eCOMMON_CONSTANT_CHARGE_ACTIVITY_MAX);
		this.m_kConstantCode.InsertCodeValue("EXTRACT_HEARTSCOUNT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_EXTRACT_HEARTSCOUNT);
		this.m_kConstantCode.InsertCodeValue("EXTRACT_ITEMUNIQUE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_EXTRACT_ITEMUNIQUE);
		this.m_kConstantCode.InsertCodeValue("ESSENCE_ITEMUNIQUE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_ESSENCE_ITEMUNIQUE);
		this.m_kConstantCode.InsertCodeValue("ESSENCECOUNT_FORONE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_ESSENCECOUNT_FORONE);
		this.m_kConstantCode.InsertCodeValue("BABEL_REPEAT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_BABEL_REPEAT);
		this.m_kConstantCode.InsertCodeValue("LEGEND_TIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_LEGEND_TIME);
		this.m_kConstantCode.InsertCodeValue("CARD_MULTIPLE_OPEN", eCOMMON_CONSTANT.eCOMMON_CONSTANT_CARD_MULTIPLE_OPEN);
		this.m_kConstantCode.InsertCodeValue("TRANSCENDENCE_ITEMUNIQUE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_TRANSCENDENCE_ITEMUNIQUE);
		this.m_kConstantCode.InsertCodeValue("FASTBATTLE_MAX", eCOMMON_CONSTANT.eCOMMON_CONSTANT_FASTBATTLE_MAXNUM);
		this.m_kConstantCode.InsertCodeValue("MYTHRAID_UNIQUE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_MYTHRAID_UNIQUE);
		this.m_kConstantCode.InsertCodeValue("FASTBATTLE_MAX", eCOMMON_CONSTANT.eCOMMON_CONSTANT_FASTBATTLE_MAXNUM);
		this.m_kConstantCode.InsertCodeValue("INFIBATTLE_CHARGEMAX", eCOMMON_CONSTANT.eCOMMON_CONSTANT_INFIBATTLE_CHARGEMAX);
		this.m_kConstantCode.InsertCodeValue("INFIBATTLE_CHARGETIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_INFIBATTLE_CHARGETIME);
		this.m_kConstantCode.InsertCodeValue("INFIBATTLE_REALTIMERANK", eCOMMON_CONSTANT.eCOMMON_CONSTANT_INFIBATTLE_RANK);
		this.m_kConstantCode.InsertCodeValue("LEGEND_ADVENT_HERO", eCOMMON_CONSTANT.eCOMMON_CONSTANT_LEGEND_ADVENT_HERO);
		this.m_kConstantCode.InsertCodeValue("ITEMSKILLREINFORCE_DOWN", eCOMMON_CONSTANT.eCOMMON_CONSTANT_ITEMSKILLREINFORCE_DOWN);
		this.m_kConstantCode.InsertCodeValue("ITEMSKILLREINFORCE_DESTORY", eCOMMON_CONSTANT.eCOMMON_CONSTANT_ITEMSKILLREINFORCE_DESTORY);
		this.m_kConstantCode.InsertCodeValue("ITEMSKILLREINFORCE_MAXLEVEL", eCOMMON_CONSTANT.eCOMMON_CONSTANT_ITEMSKILLREINFORCE_MAXLEVEL);
		this.m_kConstantCode.InsertCodeValue("ITEMREPAIR_LIMIT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_ITEMREPAIR_LIMIT);
		this.m_kConstantCode.InsertCodeValue("MYTHRAID_LIMIT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_MYTHRAID_LIMITLEVEL);
		this.m_kConstantCode.InsertCodeValue("TRANSCENDENCE_PLUSRATE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_TRANSCENDENCE_PLUSRATE);
		this.m_kConstantCode.InsertCodeValue("INFIBATTLE_BLIND_MATCH_TIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_INFIBATTLE_BLIND_MATCH_TIME);
		this.m_kConstantCode.InsertCodeValue("COSTUME_PRICE_ITEM_UNIQUE_1", eCOMMON_CONSTANT.eCOMMON_CONSTANT_COSTUME_PRICE_ITEM_UNIQUE_1);
		this.m_kConstantCode.InsertCodeValue("COSTUME_PRICE_ITEM_UNIQUE_2", eCOMMON_CONSTANT.eCOMMON_CONSTANT_COSTUME_PRICE_ITEM_UNIQUE_2);
		this.m_kConstantCode.InsertCodeValue("TIMESHOP_REFRESH_TIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_TIMESHOP_REFRESH_TIME);
		this.m_kConstantCode.InsertCodeValue("TIMESHOP_REFRESH_FORBIDDEN_TIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_TIMESHOP_REFRESH_FORBIDDEN_TIME);
		this.m_kConstantCode.InsertCodeValue("TIMESHOP_MIN_SLOTCOUNT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_TIMESHOP_MIN_SLOTCOUNT);
		this.m_kConstantCode.InsertCodeValue("FREE_TICKET_PREMINUM_TIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_FREETICKET_PREMINUM_TIME);
		this.m_kConstantCode.InsertCodeValue("FREE_TICKET_HEARTS_TIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_FREETICKET_HEARTS_TIME);
		this.m_kConstantCode.InsertCodeValue("ATTEND_RETURN_USER", eCOMMON_CONSTANT.eCOMMON_CONSTANT_ATTEND_RETURN_USER);
		this.m_kConstantCode.InsertCodeValue("DD_REPEAT_LIMIT", eCOMMON_CONSTANT.eCOMMON_CONSTANT_DAILYDUNGEON_LIMIT);
		this.m_kConstantCode.InsertCodeValue("DD_REPEAT_COST_PLUS", eCOMMON_CONSTANT.eCOMMON_CONSTANT_DAILYDUNGEON_COST_PLUS);
		this.m_kConstantCode.InsertCodeValue("DD_COUNT_BASE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_DAILYDUNGEON_COUNT_BASE);
		this.m_kConstantCode.InsertCodeValue("TIMESHOP_TYPE_SLOTNUM", eCOMMON_CONSTANT.eCOMMON_CONSTANT_TIMESHOP_TYPE_SLOTNUM);
		this.m_kConstantCode.InsertCodeValue("HUNT_LIMITLEVEL", eCOMMON_CONSTANT.eCOMMON_CONSTANT_HUNT_LIMITLEVEL);
		this.m_kConstantCode.InsertCodeValue("DAILYDUNGEON_LIMITLEVEL", eCOMMON_CONSTANT.eCOMMON_CONSTANT_DAILYDUNGEON_LIMITLEVEL);
		this.m_kConstantCode.InsertCodeValue("NORMAL_ITEMSKILLREINFORCE_DOWN", eCOMMON_CONSTANT.eCOMMON_CONSTANT_NORMAL_ITEMSKILLREINFORCE_DOWN);
		this.m_kConstantCode.InsertCodeValue("NORMAL_ITEMSKILLREINFORCE_DESTORY", eCOMMON_CONSTANT.eCOMMON_CONSTANT_NORMAL_ITEMSKILLREINFORCE_DESTORY);
		this.m_kConstantCode.InsertCodeValue("NORMAL_ITEMSKILLREINFORCE_MAXLEVEL", eCOMMON_CONSTANT.eCOMMON_CONSTANT_NORMAL_ITEMSKILLREINFORCE_MAXLEVEL);
		this.m_kConstantCode.InsertCodeValue("MYTHSKILUP_REQUIRE_ITEMUNIQUE", eCOMMON_CONSTANT.eCOMMON_CONSTANT_MYTH_SKILL_ITEMUNIQUE);
		this.m_kConstantCode.InsertCodeValue("MYTHEVOLUTION_TIME", eCOMMON_CONSTANT.eCOMMON_CONSTANT_MYTH_EVOLUTION_TIME);
	}

	public eCOMMON_CONSTANT GetConstantCode(string strConstantConde)
	{
		return this.m_kConstantCode.GetValue(strConstantConde);
	}

	public void SetData(eCOMMON_CONSTANT eConst, int value)
	{
		if (eConst < (eCOMMON_CONSTANT)0 || eConst >= eCOMMON_CONSTANT.eCOMMON_CONSTANT_MAX)
		{
			return;
		}
		this.m_CommonConstant[(int)eConst] = value;
	}

	public int GetValue(eCOMMON_CONSTANT Const)
	{
		if (Const < (eCOMMON_CONSTANT)0 || Const >= eCOMMON_CONSTANT.eCOMMON_CONSTANT_MAX)
		{
			return 0;
		}
		return this.m_CommonConstant[(int)Const];
	}

	public override bool ParseDataFromNDT(TsDataReader dr)
	{
		foreach (TsDataReader.Row data in dr)
		{
			COMMON_CONSTANT cOMMON_CONSTANT = new COMMON_CONSTANT();
			cOMMON_CONSTANT.SetData(data);
			cOMMON_CONSTANT.m_eConstant = this.GetConstantCode(cOMMON_CONSTANT.strConstant);
			this.SetData(cOMMON_CONSTANT.m_eConstant, cOMMON_CONSTANT.m_nConstant);
		}
		return true;
	}
}
