using System;

public enum E_NPC_TALK_STEP
{
	E_NPC_TALK_STEP_START,
	E_NPC_TALK_STEP_MENU,
	E_NPC_TALK_STEP_TALK,
	E_NPC_TALK_STEP_PREACCEPT,
	E_NPC_TALK_STEP_ACCEPT,
	E_NPC_TALK_STEP_PRECOMPETE,
	E_NPC_TALK_STEP_COMPETE,
	E_NPC_TALK_STEP_REWARD,
	E_NPC_TALK_STEP_NONE,
	E_NPC_TALK_STEP_END
}
