using System;

public enum eSOLDIER_BATCH_MODE
{
	MODE_PLUNDER,
	MODE_ATTACK_MAKEUP,
	MODE_DEFENCE_MAKEUP,
	MODE_PVP_MAKEUP,
	MODE_PVP_MAKEUP2,
	MODE_BABEL_TOWER,
	MODE_MINE_MAKEUP,
	MODE_GUILDBOSS_MAKEUP,
	MODE_INFIBATTLE,
	MODE_ATTACK_INFIBATTLE_MAKEUP,
	MODE_DEFENSE_INFIBATTLE_MAKEUP,
	MODE_PRACTICE_INFIBATTLE,
	MODE_EXPEDITION_MAKEUP,
	MODE_GUILDWAR_MAKEUP,
	MODE_MAX
}
