using System;

public enum eTMLOBBY_STEP
{
	eTMLOBBY_STEP_NONE,
	eTMLOBBY_STEP_OPEN,
	eTMLOBBY_STEP_BAN_1,
	eTMLOBBY_STEP_BAN_2,
	eTMLOBBY_STEP_BAN_3,
	eTMLOBBY_STEP_BAN_4,
	eTMLOBBY_STEP_SELECT_1,
	eTMLOBBY_STEP_SELECT_2,
	eTMLOBBY_STEP_SELECT_3,
	eTMLOBBY_STEP_SELECT_4,
	eTMLOBBY_STEP_CHANGE_POS,
	eTMLOBBY_STEP_END,
	eTMLOBBY_STEP_MAX
}
