using System;

public enum eWHISPERMENU
{
	eEWHISPERMENU_NONE,
	eEWHISPERMENU_SHOW_DETAIL_INFO,
	eEWHISPERMENU_WHISPER,
	eEWHISPERMENU_FOLLOW,
	eEWHISPERMENU_POSTSEND,
	eEWHISPERMENU_FRIEND_DEL,
	eEWHISPERMENU_FRIEND_ADD,
	eWHISPERMENU_USER_KICK,
	eEWHISPERMENU_WARP,
	eEWHISPERMENU_END
}
