using System;

public enum eWHISPER_RESULTMSG
{
	eRESULT_NOTTARGETPLAYER,
	eRESULT_PLAYERJOIN,
	eRESULT_PLAYERGOOUT,
	eRESULT_CHATBLOCKUSER,
	eRESULT_INVITE_SEND,
	eRESULT_INVITE_NO,
	eRESULT_NOMYTARGETPLAYER
}
