using System;

public class NrCharKindTempData
{
	public CHARKIND_INFO m_pkCHARKIND_INFO;

	public CHARKIND_CLASSINFO m_pkCHARKIND_CLASSINFO;

	public CHARKIND_ATTACKINFO m_pkCHARKIND_ATTACKINFO;

	public CHARKIND_STATINFO m_pkCHARKIND_STATINFO;

	public CHARKIND_MONSTERINFO m_pkCHARKIND_MONSTERINFO;

	public CHARKIND_MONSTATINFO m_pkCHARKIND_MONSTATINFO;

	public CHARKIND_NPCINFO m_pkCHARKIND_NPCINFO;

	public CHARKIND_SOLDIERINFO m_pkCHARKIND_SOLDIERINFO;

	public CHARKIND_SOLGRADEINFO m_pkCHARKIND_SOLGRADEINFO;

	public NrCharKindTempData()
	{
		this.m_pkCHARKIND_INFO = new CHARKIND_INFO();
		this.m_pkCHARKIND_CLASSINFO = new CHARKIND_CLASSINFO();
		this.m_pkCHARKIND_ATTACKINFO = new CHARKIND_ATTACKINFO();
		this.m_pkCHARKIND_STATINFO = new CHARKIND_STATINFO();
		this.m_pkCHARKIND_MONSTERINFO = new CHARKIND_MONSTERINFO();
		this.m_pkCHARKIND_MONSTATINFO = new CHARKIND_MONSTATINFO();
		this.m_pkCHARKIND_NPCINFO = new CHARKIND_NPCINFO();
		this.m_pkCHARKIND_SOLDIERINFO = new CHARKIND_SOLDIERINFO();
		this.m_pkCHARKIND_SOLGRADEINFO = new CHARKIND_SOLGRADEINFO();
	}
}
