using System;

public enum SYSTEM_MESSAGE_TYPE : byte
{
	NORMAL_MESSAGE,
	NAGATIVE_MESSAGE,
	CAUTION_MESSAGE,
	IMPORTANT_MESSAGE,
	NORMAL_SYSTEM_MESSAGE,
	ADMIN_SYSTEM_MESSAGE,
	QUEST_COMLPETE,
	BATTLE_SHOWTEXT_MODE4,
	NORMAL_MESSAGE_GREEN,
	BATTLE_RADIO_ALARM,
	DEBUG_MESSAGE
}
