using System;

public enum eBABELTOWER_CHARSET
{
	eBABELTOWER_CHARSET_NONE,
	eBABELTOWER_CHARSET_INSERT,
	eBABELTOWER_CHARSET_DELETE,
	eBABELTOWER_CHARSET_CHANGE,
	eBABELTOWER_CHARSET_CHANGE_DELETE,
	eBABELTOWER_CHARSET_REFLASH
}
