using System;

public enum eBATTLE_SKILL_INPUT_INDEX
{
	eBATTLE_SKILL_INPUT_INDEX_EMPTY = -1,
	eBATTLE_SKILL_INPUT_INDEX_1 = 1,
	eBATTLE_SKILL_INPUT_INDEX_2,
	eBATTLE_SKILL_INPUT_INDEX_3,
	eBATTLE_SKILL_INPUT_INDEX_4,
	eBATTLE_SKILL_INPUT_INDEX_MAX
}
