using System;

public enum eBATTLE_ROOM_STATE
{
	eBATTLE_ROOM_STATE_NONE,
	eBATTLE_ROOM_STATE_OPEN,
	eBATTLE_ROOM_STATE_READY,
	eBATTLE_ROOM_STATE_ACTION,
	eBATTLE_ROOM_STATE_WAIT_CONTINUE,
	eBATTLE_ROOM_STATE_WAIT_END,
	eBATTLE_ROOM_STATE_END,
	eBATTLE_ROOM_STATE_MAX
}
