using System;

public enum eBATTLE_RADIO_ALARM
{
	eBATTLE_RADIO_ALARM_THANK,
	eBATTLE_RADIO_ALARM_SORRY,
	eBATTLE_RADIO_ALARM_ATTACK,
	eBATTLE_RADIO_ALARM_GOOD,
	eBATTLE_RADIO_ALARM_BYEBYE,
	eBATTLE_RADIO_ALARM_MAX
}
