using System;

public enum eBATTLE_CHARINFO_REASON
{
	eBATTLE_CHARINFO_REASON_INCLIFE,
	eBATTLE_CHARINFO_REASON_INCMANA,
	eBATTLE_CHARINFO_REASON_HIT,
	eBATTLE_CHARINFO_REASON_EXP,
	eBATTLE_CHARINFO_REASON_LEVEL,
	eBATTLE_CHARINFO_REASON_USEITEMRESERVE,
	eBATTLE_CHARINFO_REASON_DEAD,
	eBATTLE_CHARINFO_REASON_REBIRTH,
	eBATTLE_CHARINFO_REASON_DELETECHAR,
	eBATTLE_CHARINFO_REASON_SETBUFFSKILL,
	eBATTLE_CHARINFO_REASON_MAX
}
