using System;

public enum eBATTLE_MOVE_STATUS
{
	eBATTLE_MOVE_STATUS_NORMAL,
	eBATTLE_MOVE_STATUS_STOP,
	eBATTLE_MOVE_STATUS_RENEWPOS,
	eBATTLE_MOVE_STATUS_WAIT,
	eBATTLE_MOVE_STATUS_CHANGEPOS,
	eBATTLE_MOVE_STATUS_MAX
}
