using System;

public enum eBATTLE_ORDER
{
	eBATTLE_ORDER_NONE,
	eBATTLE_ORDER_MOVE,
	eBATTLE_ORDER_ATTACK,
	eBATTLE_ORDER_SKILL,
	eBATTLE_ORDER_ATTACK_LAND,
	eBATTLE_ORDER_SEARCH,
	eBATTLE_ORDER_CHANGEPOS,
	eBATTLE_ORDER_RUNAWAY,
	eBATTLE_ORDER_MAX
}
