using System;

public enum eBATTLE_CHARTYPE
{
	BATTLE_CHARTYPE_NONE,
	BATTLE_CHARTYPE_MONSTER,
	BATTLE_CHARTYPE_FRIEND,
	BATTLE_CHARTYPE_CHANGESOL = 4,
	BATTLE_CHARTYPE_DEFENCEOBJECT = 8,
	BATTLE_CHARTYPE_REVIVECHAR = 16
}
