using System;

public enum eBATTLE_EMOTICON
{
	eBATTLE_EMOTICON_ATTACK,
	eBATTLE_EMOTICON_HEAL,
	eBATTLE_EMOTICON_IGNORE,
	eBATTLE_EMOTICON_ANGER,
	eBATTLE_EMOTICON_MAZZ,
	eBATTLE_EMOTICON_ANGRY,
	eBATTLE_EMOTICON_NERVOUS,
	eBATTLE_EMOTICON_SMILE,
	eBATTLE_EMOTICON_THANK,
	eBATTLE_EMOTICON_MAX
}
