using System;

public enum eBATTLE_CHARSTATEATB
{
	BATTLE_CHARSTATEATB_DISABLE_NONE,
	BATTLE_CHARSTATEATB_DISABLE_MOVE,
	BATTLE_CHARSTATEATB_DISABLE_ATTACK,
	BATTLE_CHARSTATEATB_IMMUNE = 4,
	BATTLE_CHARSTATEATB_DISABLE_TURN = 8,
	BATTLE_CHARSTATEATB_IMMORTAL = 16,
	BATTLE_CHARSTATEATB_SILENCE = 32,
	BATTLE_CHARSTATEATB_OBJECT = 64,
	BATTLE_CHARSTATEATB_NOCONTROL = 128,
	BATTLE_CHARSTATEATB_NOCON_NOTARGETING = 256,
	BATTLE_CHARSTATEATB_NO_SKILLTARGETING = 512,
	BATTLE_CHARSTATEATB_IMMUNE_SKILL = 1024,
	BATTLE_CHARSTATEATB_SLEEP = 2048,
	BATTLE_CHARSTATEATB_MARKING = 4096,
	BATTLE_CHARSTATEATB_DISABLE_NOMALATTACK = 8192,
	BATTLE_CHARSTATEATB_IMMUNE_NOTURN_ON = 16384,
	BATTLE_CHARSTATEATB_IMMUNE_NOSKILL_ON = 32768,
	BATTLE_CHARSTATEATB_WEAKPOINT_ON = 65536,
	BATTLE_CHARSTATEATB_WEAKPOINT_ON_ONE = 131072,
	BATTLE_CHARSTATEATB_IMMUNE_NOCONTROL_ON = 262144,
	BATTLE_CHARSTATEATB_NO_SKILLTARGETING_E = 524288,
	BATTLE_CHARSTATEATB_IMMUNE_BOSS = 1048576,
	BATTLE_CHARSTATEATB_MAGIC_RESIST = 2097152,
	BATTLE_CHARSTATEATB_PHYSICAL_RESIST = 4194304
}
