using System;

public enum eBATTLE_ROOMTYPE
{
	eBATTLE_ROOMTYPE_NONE,
	eBATTLE_ROOMTYPE_NORMAL,
	eBATTLE_ROOMTYPE_SCENARIO,
	eBATTLE_ROOMTYPE_PVE,
	eBATTLE_ROOMTYPE_PVP,
	eBATTLE_ROOMTYPE_PLUNDER,
	eBATTLE_ROOMTYPE_COLOSSEUM,
	eBATTLE_ROOMTYPE_BABELTOWER,
	eBATTLE_ROOMTYPE_MINE,
	eBATTLE_ROOMTYPE_GUILD_BOSS,
	eBATTLE_ROOMTYPE_DAILYDUNGEON,
	eBATTLE_ROOMTYPE_INFINITY,
	eBATTLE_ROOMTYPE_BOUNTYHUNT,
	eBATTLE_ROOMTYPE_EXPEDITION,
	eBATTLE_ROOMTYPE_TUTORIAL,
	eBATTLE_ROOMTYPE_MYTHRAID,
	eBATTLE_ROOMTYPE_PREVIEW,
	eBATTLE_ROOMTYPE_NEWEXPLORATION,
	eBATTLE_ROOMTYPE_MAX
}
