using System;

public class QUEST_CONST
{
	public enum eQUESTCODE
	{
		QUESTCODE_START,
		QUESTCODE_AUTOBATTLE,
		QUESTCODE_AUTOMOVE,
		QUESTCODE_BACK_GEN_TO_PLACE,
		QUESTCODE_GO_GEN_TO_WORLD,
		QUESTCODE_BACK_SOL_TO_PLACE,
		QUESTCODE_GO_SOL_TO_WORLD,
		QUESTCODE_GETITEM,
		QUESTCODE_BRINGITEM,
		QUESTCODE_BUILDINPLACE,
		QUESTCODE_BUYMARKET,
		QUESTCODE_REPAIRITEM,
		QUESTCODE_BREAKITEM,
		QUESTCODE_FAILWAR,
		QUESTCODE_VICTORYWAR,
		QUESTCODE_GETMONEY,
		QUESTCODE_CREATEITEM,
		QUESTCODE_SIGNUPITEM,
		QUESTCODE_EQUIPITEM,
		QUESTCODE_GOPLACE = 22,
		QUESTCODE_GODUNGEON = 29,
		QUESTCODE_GONPC,
		QUESTCODE_OPENMILITARY,
		QUESTCODE_MILITARYFORMATION,
		QUESTCODE_PILLAGE,
		QUESTCODE_KILLMONSTER = 36,
		QUESTCIDE_WORLDMAPWARP = 40,
		QUESTCODE_EQUIPMENT,
		QUESTCODE_EQUIPSOL,
		QUESTCODE_COLLECTITEM,
		QUESTCODE_MAKEVOLUNTEER = 46,
		QUESTCODE_GIVEITEM = 48,
		QUESTCODE_LEARNBATTLESKILL = 51,
		QUESTCODE_GETLETTER = 54,
		QUESTCODE_SENDLETTER,
		QUESTCODE_COMBATPOWER = 58,
		QUESTCODE_GENITEMGRADE,
		QUESTCODE_OPENIVENTORY = 63,
		QUESTCODE_OPENMAP,
		QUESTCODE_PRODUCEHP,
		QUESTCODE_PRODUCEHUMAN,
		QUESTCODE_PRODUCERESOURCE,
		QUESTCODE_USEITEM,
		QUESTCODE_USEMAGIC = 85,
		QUESTCODE_LEVELSOL = 89,
		QUESTCODE_OPENTRANSMAP,
		QUESTCODE_OPENSOLDIER,
		QUESTCODE_LEVELMAKE,
		QUESTCODE_LEARNMAKE,
		QUESTCODE_LEVELCHARACTER = 95,
		QUESTCODE_FOLLOWCHAR,
		QUESTCODE_OPENGENERALLIST,
		QUESTCODE_OPENMAKE,
		QUESTCODE_ACCEPT_BRINGCHAR,
		QUESTCODE_UPGRADEITEM,
		QUESTCODE_TRAINNING_MONSTER,
		QUESTCODE_OPENEQUIPWINDOW,
		QUESTCODE_GUARDCHAR,
		QUESTCODE_AMASSITEM,
		QUESTCODE_HUNTCHAR,
		QUESTCODE_EQUIPTHISITEM,
		QUESTCODE_QUESTMAKE,
		QUESTCODE_GATHERITEM,
		QUESTCODE_CHECKDEFENSE,
		QUESTCODE_OPENDOCTOR,
		QUESTCODE_STANDBYGENERAL,
		QUESTCODE_OPENCOLLECT,
		QUESTCODE_CLEARBABEL,
		QUESTCODE_SAMPOOMHELP,
		QUESTCODE_SELLITEM,
		QUESTCODE_PARTYKILLMONSTER,
		QUESTCODE_PARTYVICTORYSCENARIOBATTLE,
		QUESTCODE_PASSTURN,
		QUESTCODE_AUTOBATTLEON,
		QUESTCODE_AUTOBATTLEOFF,
		QUESTCODE_TAKECHAR = 122,
		QUESTCODE_JOINCOLOSSEUM,
		QUESTCODE_GENERALCHANGE,
		QUESTCODE_VICTORYBATTLEMATCH,
		QUESTCODE_BATTLEMATCHLIST,
		QUESTCODE_WATCHBATTLEMATCH,
		QUESTCODE_EXPEDITION,
		QUESTCODE_CHECKSOL,
		QUESTCODE_PROGRESSINFO,
		QUESTCODE_GENERAL_SCOUT = 132,
		QUESTCODE_MYSOLDIER,
		QUESTCODE_CHATTINGMACRO,
		QUESTCODE_MYMENU,
		QUESTCODE_GREET,
		QUESTCODE_MAKEFRIEND,
		QUESTCODE_SHOWCOMMUNITY,
		QUESTCODE_CUISINE,
		QUESTCODE_OPENQUESTLIST,
		QUESTCODE_OPENDRAMALIST,
		QUESTCODE_OPENCOMMUNITY,
		QUESTCODE_JOINGUILD,
		QUESTCODE_MAKESKILL,
		QUESTCODE_MAKE_EQUIP,
		QUESTCODE_UPGRADE_EQUIP,
		QUESTCODE_GO_GEN_TO_NUM = 149,
		QUESTCODE_SOLITEM_GRADE_COUNT,
		QUESTCODE_BACK_GEN_TO_PLACE2,
		QUESTCODE_GO_SOL_TO_WORLD2,
		QUESTCODE_REBIRTH,
		QUESTCODE_FREEBUILD,
		QUESTCODE_WINBATTLE,
		QUESTCODE_RELOCATE_BUILDING,
		QUESTCODE_DESTROY_BUILDING,
		QUESTCOODE_EXPAND_INVENTORY,
		QUESTCODE_AMASSITEMUSE,
		QUESTCODE_CAREANIMAL,
		QUESTCODE_USEITEM2,
		QUESTCODE_HARVESTFOOD,
		QUESTCODE_STORAGEFOOD,
		QUESTCODE_SUCCESSREPUTE,
		QUESTCODE_NORMALWINBATTLE,
		QUESTCODE_CONTINUEBATTLE,
		QUESTCODE_TRIGGER_CHECK = 999,
		QUESTCODE_END
	}

	public enum eQUESTSTATE : byte
	{
		QUESTSTATE_END,
		QUESTSTATE_COMPLETE_OTHER,
		QUESTSTATE_FAIL,
		QUESTSTATE_NOT_ACCEPTABLE_NOT_VIEW,
		QUESTSTATE_NOT_ACCEPTABLE_VIEW,
		QUESTSTATE_ACCEPTABLE,
		QUESTSTATE_ONGOING,
		QUESTSTATE_COMPLETE,
		QUESTSTATE_NONE,
		QUESTSTATE_DAYQUEST_ACCEPTABLE,
		QUESTSTATE_DAYQUEST_COMPLETE
	}

	public enum eAcceptCheck
	{
		eAcceptCheck_None,
		eAcceptCheck_Item
	}

	public enum E_QUEST_GROUP_STATE
	{
		E_QUEST_GROUP_STATE_NONE,
		E_QUEST_GROUP_STATE_ONGONIG,
		E_QUEST_GROUP_STATE_EVEN
	}

	public enum E_QUEST_END_TYPE
	{
		QUEST_END_TYPE_NPC,
		QUEST_END_TYPE_CONDITION_COMPLETE_IMMEDIATELY,
		QUEST_END_TYPE_TRIGGER
	}

	public enum E_DLG_NPC_TALK_STATE
	{
		E_DLG_NPC_TALK_STATE_RIGHT_TALK,
		E_DLG_NPC_TALK_STATE_LEFT_TALK,
		E_DLG_NPC_TALK_STATE_RIGHT_TALK_NONE,
		E_DLG_NPC_TALK_STATE_LEFT_TALK_NONE
	}

	public enum E_QUEST_TYPE
	{
		E_QUEST_TYPE_MAIN = 1,
		E_QUEST_TYPE_SUB,
		E_QUEST_TYPE_DAY = 100,
		E_QUEST_TYPE_TERRITORY = 200,
		E_QUEST_TYPE_TOTAL = 999
	}

	public enum E_QUEST_TAKE_CHAR_CON
	{
		E_QUEST_TAKE_CHAR_CON_NONE = 30,
		E_QUEST_TAKE_CHAR_CON_MONEY = 15,
		E_QUEST_TAKE_CHAR_CON_ITEM = 48
	}

	public const short QUEST_GROUP_MAX = 13;

	public const byte USER_CURRENT_QUEST_MAX = 10;

	public const byte QUEST_CONDITION_MAX = 3;

	public const byte QUEST_REWARD_MAX = 5;

	public const byte PRE_QUEST_ACCEPT_CHECK_MAX = 3;

	public const short QUEST_PER_GROUP_MAX = 200;

	public const byte REWARD_ITEM_MAX = 5;

	public const byte QUEST_GROUP_BYTE = 25;

	public const byte QUEST_GRADE_NUM = 5;

	public const byte QUEST_CONTEXT_LENGTH_MAX = 40;

	public const byte QUEST_UNIQUE_LENGTH = 33;

	public const int E_REWARD_TYPE_NONE = 1;

	public const int E_REWARD_TYPE_EXP = 2;

	public const int E_REWARD_TYPE_MONEY = 4;

	public const int E_REWARD_TYPE_REPUTE = 8;

	public const int E_REWARD_TYPE_ITEM = 16;

	public const int E_REWARD_TYPE_SOLDIER_RECRUIT = 32;

	public const int E_REWARD_TYPE_GENREAL_UPGRADE = 64;

	public const int E_REWARD_TYPE_SOLDIER_RECRUIT_ITEM = 128;

	public const int E_REWARD_TYPE_GENREAL_UPGRADE_ITEM = 256;

	public const int E_REWARD_TYPE_GROUP_CLEAR = 512;

	public const long DLG_OPTION_CHAR_NOT_VIEW = 1L;

	public const long DLG_OPTION_CAMERA_SHAKE = 2L;

	public const long DLG_OPTION_CHAR_INFO = 4L;

	public const long DLG_OPTION_SOUND = 8L;

	public const long DLG_IMAGE_RIGHT = 16L;

	public const long DLG_IMAGE_LEFT = 32L;

	public const long DLG_FADE_WHITE = 64L;

	public const long DLG_FADE_BLACK = 128L;

	public const int MAX_DAYQUEST_COMPLETED_COUNT = 15;
}
