using System;

namespace PROTOCOL.MESSAGE.ID
{
	public enum eMESSAGE_ID
	{
		MESSAGE_TEST = 10,
		MESSAGE_MARKET_ITEMSOLD = 100,
		MESSAGE_MAKEITEM_COMPLETED = 200,
		MESSAGE_GUILD_MEMBER_JOINED = 300,
		MESSAGE_GUILD_MEMBER_LEFT,
		MESSAGE_GUILD_MEMBER_RANK_CHANGED,
		MESSAGE_FRIEND_LOGIN = 400,
		MESSAGE_FRIEND_LOGOUT,
		MESSAGE_NEW_MAIL = 500
	}
}
